* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-16T14:08:21.472313+00:00.
* Survey source: (V9 R98676) CRA-Astellas_Dravet_Syndrome_HCP_Survey_v28May2026.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AUTOQ1: no validation emitted - Consent question terminates flow; single binary response, no macro check needed for validation logic beyond standard single-punch (no macro applies to simple consent)..

* AUTOQ2: no validation emitted - Single binary terminate-logic screener question; no multi/rank/sum macro applies..

* AUTOQ3: no validation emitted - Single binary terminate-logic screener question; no multi/rank/sum macro applies..

* AUTOQ5: no validation emitted - Single binary consent-style question; no macro applies..

* PT10: no validation emitted - Single binary pre-test availability question; no macro applies..

* PT20: no validation emitted - Single binary pre-test consent question; no macro applies..

* AUTOQ6: no validation emitted - Single-select specialty screener (variable s10); standard single-punch, no multi/sum/rank macro needed..

* AUTOQ7: no validation emitted - Single-select board certification screener (variable s20); no macro applies..

* AUTOQ8: no validation emitted - Single binary certification screener; no macro applies..

***************************************AUTOQ9.
tit AUTOQ9 - Years in practice out of allowed range (0-100).
if(s40_1 < 0 or s40_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s40_1.
DELETE VARIABLES flag.

* AUTOQ10: no validation emitted - Single-select country screener (variable s50); no macro applies..

***************************************AUTOQ11.
!SUM_TO_VAR svar=s70_1 evar=s70_98 qnt=AUTOQ11 opr==.

***************************************AUTOQ12.
tit AUTOQ12 - Patient counts (S80) out of allowed range (0-100).
if(s80_1 < 0 or s80_1 > 100 or s80_2 < 0 or s80_2 > 100 or s80_3 < 0 or s80_3 > 100 or s80_4 < 0 or s80_4 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_1 s80_2 s80_3 s80_4.
DELETE VARIABLES flag.

***************************************S85.
!SUM_TO_VAR svar=s85_1 evar=s85_5 qnt=S85 opr==.

***************************************AUTOQ13.
!MULTI_A svar=s90_1 evar=s90_98 qnt=AUTOQ13.

***************************************AUTOQ14.
tit AUTOQ14 - S100_1 (MR/pharma association) missing.
if(miss(s100_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_1.
DELETE VARIABLES flag.
tit AUTOQ14 - S100_2 (compensated by pharma) missing.
if(miss(s100_2)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_2.
DELETE VARIABLES flag.
tit AUTOQ14 - S100_3 (ethics compliance reason) missing.
if(miss(s100_3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_3.
DELETE VARIABLES flag.

***************************************AUTOQ15.
!SUM_TO_VAR svar=q10_1 evar=q10_98 qnt=AUTOQ15 opr==.
tit AUTOQ15 - Q10DK (I don't know) selected alongside substantive insurance percentages.
if(q10dk_99 = 1 and (sum(q10_1,q10_2,q10_3,q10_4,q10_98) > 0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q10dk_99 q10_1 q10_2 q10_3 q10_4 q10_98.
DELETE VARIABLES flag.

***************************************AUTOQ16.
!SUM_TO_VAR svar=q20_1 evar=q20_2 qnt=AUTOQ16 opr==.

***************************************AUTOQ17.
tit AUTOQ17 - Q30_1 confirmed SCN1A mutation percentage out of range (0-100).
if(q30_1 < 0 or q30_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q30_1.
DELETE VARIABLES flag.

***************************************AUTOQ18.
!MULTI_A svar=q40_1 evar=q40_98 qnt=AUTOQ18.

***************************************AUTOQ19.
tit AUTOQ19 - Prevalence perception not answered.
if(miss(q50_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q50_1.
DELETE VARIABLES flag.

***************************************AUTOQ20.
tit AUTOQ20 - Diagnosed prevalence out of allowed range (1-100K).
if(q60x_1 < 1 or q60x_1 > 100000) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q60x_1.
DELETE VARIABLES flag.

***************************************AUTOQ21.
tit AUTOQ21 - Diagnosis rate change perception not answered.
if(miss(q70)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70.
DELETE VARIABLES flag.

***************************************AUTOQ22.
tit AUTOQ22 - Q90_1 expected when Q70=3 (increase) but missing.
if(q70 = 3 and miss(q90_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70 q90_1.
DELETE VARIABLES flag.
tit AUTOQ22 - Diagnosis rate increase % out of range 0-100.
if(q90_1 < 0 or q90_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q90_1.
DELETE VARIABLES flag.

***************************************AUTOQ23.
!SUM_TO_VAR svar=q100_1 evar=q100_3 qnt=AUTOQ23.

***************************************AUTOQ24.
!SUM_TO_VAR svar=q110_1 evar=q110_5 qnt=AUTOQ24.

***************************************AUTOQ25.
!MULTI_B svar=q120x1_1 evar=q120x1_98 qnt=AUTOQ25.
!MULTI_B svar=q120x2_1 evar=q120x2_98 qnt=AUTOQ25.
!MULTI_B svar=q120x3_1 evar=q120x3_98 qnt=AUTOQ25.
!MULTI_B svar=q120x4_1 evar=q120x4_98 qnt=AUTOQ25.
!MULTI_B svar=q120x5_1 evar=q120x5_98 qnt=AUTOQ25.

***************************************AUTOQ26.
!SUM_TO_VAR svar=q130x1_1 evar=q130x1_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x2_1 evar=q130x2_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x3_1 evar=q130x3_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x4_1 evar=q130x4_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x5_1 evar=q130x5_4 qnt=AUTOQ26.

***************************************AUTOQ27.
!MULTI_A svar=q140_1 evar=q140_98 qnt=AUTOQ27.

***************************************AUTOQ28.
tit AUTOQ28 - Good seizure control % reduction out of range 0-100.
if(q150_1 < 0 or q150_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q150_1.
DELETE VARIABLES flag.

***************************************AUTOQ29.
tit AUTOQ29 - % second line patients not achieving good control out of range 0-100.
if(q160_1 < 0 or q160_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q160_1.
DELETE VARIABLES flag.

***************************************AUTOQ30.
tit AUTOQ30 - % patients considered for gene therapy out of range 0-100.
if(q170_1 < 0 or q170_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q170_1.
DELETE VARIABLES flag.

***************************************AUTOQ31.
tit AUTOQ31 - Initial thoughts on PRODUCT X not answered (open-end).
if(miss(q180)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q180.
DELETE VARIABLES flag.

***************************************AUTOQ32.
!MULTI_NUMB svar=q190_1 evar=q190_98 qnt=AUTOQ32.
!MULTI_B svar=q190_1 evar=q190_98 qnt=AUTOQ32.

***************************************AUTOQ33.
!MULTI_NUMB svar=q200_1 evar=q200_98 qnt=AUTOQ33.
!MULTI_B svar=q200_1 evar=q200_98 qnt=AUTOQ33.
tit AUTOQ33 - Attribute selected as advantage in Q190 also selected as disadvantage in Q200 (should be grayed out).
if(sum(q190_1,q190_2,q190_3,q190_4,q190_5,q190_6,q190_7,q190_8)>0 and range(q200_1,q200_8)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q190_1 q190_2 q190_3 q190_4 q190_5 q190_6 q190_7 q190_8 q200_1 q200_2 q200_3 q200_4 q200_5 q200_6 q200_7 q200_8.
DELETE VARIABLES flag.

* AUTOQ34: no validation emitted - No matching dataset variables found for this trial-criterion age-group grid item; cannot confidently map SPSS variable naming.

***************************************AUTOQ35.
tit AUTOQ35 - Likelihood to prescribe PRODUCT X not answered.
if(miss(q220_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q220_1.
DELETE VARIABLES flag.

***************************************AUTOQ36.
tit AUTOQ36 - Initial thoughts on PRODUCT Y not answered (open-end).
if(miss(q230)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q230.
DELETE VARIABLES flag.

***************************************AUTOQ37.
!MULTI_NUMB svar=q240_1 evar=q240_98 qnt=AUTOQ37.
!MULTI_B svar=q240_1 evar=q240_98 qnt=AUTOQ37.

***************************************AUTOQ38.
!MULTI_NUMB svar=q250_1 evar=q250_98 qnt=AUTOQ38.
!MULTI_B svar=q250_1 evar=q250_98 qnt=AUTOQ38.
tit AUTOQ38 - Attribute selected as advantage in Q240 also selected as disadvantage in Q250 (should be grayed out).
if(sum(q240_1,q240_2,q240_3,q240_4,q240_5,q240_6,q240_7,q240_8,q240_9,q240_10,q240_11,q240_12)>0 and range(q250_1,q250_12)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q240_1 q240_2 q240_3 q240_4 q240_5 q240_6 q240_7 q240_8 q240_9 q240_10 q240_11 q240_12 q250_1 q250_2 q250_3 q250_4 q250_5 q250_6 q250_7 q250_8 q250_9 q250_10 q250_11 q250_12.
DELETE VARIABLES flag.

* AUTOQ39: no validation emitted - Single-select question (q260) with no numeric range/sum/rank logic suitable for standard macros; response is a categorical single choice already constrained by radio button UI..

* AUTOQ40: no validation emitted - Single-select likelihood scale (q270_1), categorical radio, no macro applicable..

***************************************AUTOQ41.
tit AUTOQ41 - Age value outside allowed 0-100 range.
if(range(q280_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q280_1.
DELETE VARIABLES flag.

***************************************AUTOQ42.
!SUM_TO_VAR svar=q290x1_1 evar=q290x5_1 qnt=AUTOQ42.

* AUTOQ43: no validation emitted - Grid of single-select rating items (q300_1 to q300_5), each row is a single categorical choice with no sum/count/rank logic for macros..

***************************************AUTOQ44.
!SUM_TO_VAR svar=q310x1_1 evar=q310x1_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x2_1 evar=q310x2_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x3_1 evar=q310x3_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x4_1 evar=q310x4_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x5_1 evar=q310x5_98 qnt=AUTOQ44.

***************************************AUTOQ45.
tit AUTOQ45 - Switch percentage for <2 years out of 0-100 range.
if(range(q320x1_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x1_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch percentage for 2 to <4 years out of 0-100 range.
if(range(q320x2_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x2_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch percentage for 4 to <12 years out of 0-100 range.
if(range(q320x3_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x3_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch percentage for 12 to <18 years out of 0-100 range.
if(range(q320x4_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x4_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch percentage for 18+ years out of 0-100 range.
if(range(q320x5_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ46.
!SUM_TO_VAR svar=q330x1_1 evar=q330x1_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x2_1 evar=q330x2_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x3_1 evar=q330x3_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x4_1 evar=q330x4_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x5_1 evar=q330x5_98 qnt=AUTOQ46.

* AUTOQ47: no validation emitted - Single-select likelihood scale (q340_1), categorical radio, no macro applicable..

***************************************AUTOQ48.
tit AUTOQ48 - Switch percentage for <2 years out of 0-100 range.
if(range(q350x1_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x1_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch percentage for 2 to <4 years out of 0-100 range.
if(range(q350x2_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x2_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch percentage for 4 to <12 years out of 0-100 range.
if(range(q350x3_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x3_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch percentage for 12 to <18 years out of 0-100 range.
if(range(q350x4_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x4_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch percentage for 18+ years out of 0-100 range.
if(range(q350x5_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ49.
!SUM_TO_VAR svar=q360x1_1 evar=q360x1_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x2_1 evar=q360x2_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x3_1 evar=q360x3_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x4_1 evar=q360x4_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x5_1 evar=q360x5_98 qnt=AUTOQ49.

* AUTOQ50: no validation emitted - Single-select likelihood scale (q370_1), categorical radio, no macro applicable..

***************************************AUTOQ51.
tit AUTOQ51 - Switch percentage for <2 years out of 0-100 range.
if(range(q380x1_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x1_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch percentage for 2 to <4 years out of 0-100 range.
if(range(q380x2_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x2_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch percentage for 4 to <12 years out of 0-100 range.
if(range(q380x3_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x3_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch percentage for 12 to <18 years out of 0-100 range.
if(range(q380x4_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x4_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch percentage for 18+ years out of 0-100 range.
if(range(q380x5_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ52.
!SUM_TO_VAR svar=q390x1_1 evar=q390x1_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x2_1 evar=q390x2_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x3_1 evar=q390x3_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x4_1 evar=q390x4_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x5_1 evar=q390x5_98 qnt=AUTOQ52.

* AUTOQ53: no validation emitted - Single-select likelihood scale (q400_1), categorical radio, no macro applicable..

***************************************AUTOQ54.
tit AUTOQ54 - Switch percentage for <2 years out of 0-100 range.
if(range(q410x1_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x1_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch percentage for 2 to <4 years out of 0-100 range.
if(range(q410x2_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x2_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch percentage for 4 to <12 years out of 0-100 range.
if(range(q410x3_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x3_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch percentage for 12 to <18 years out of 0-100 range.
if(range(q410x4_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x4_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch percentage for 18+ years out of 0-100 range.
if(range(q410x5_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ55.
!SUM_TO_VAR svar=q420x1_1 evar=q420x1_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x2_1 evar=q420x2_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x3_1 evar=q420x3_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x4_1 evar=q420x4_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x5_1 evar=q420x5_98 qnt=AUTOQ55.

* AUTOQ56: no validation emitted - Single-select question (q430) with categorical options (Yes/No/DK/Other); no macro applicable..

***************************************AUTOQ57.
tit AUTOQ57 - Months to implement Product Y outside allowed 0-60 range.
if(range(q440_1,0,60) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q440_1.
DELETE VARIABLES flag.

* AUTOQ58: no validation emitted - Single-select 7-point receptivity scale (q450_1), categorical radio, no macro applicable..

* AUTOQ59: no validation emitted - Open-ended text response (maps to Q460); no standard macro applies to free-text verbatim..

***************************************AUTOQ60.
tit AUTOQ60 - Months for Product X out of allowed range (0-60).
if(range(0,60,q470_1)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q470_1.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 62.
* Checks emitted            : 96.
* Questions omitted         : 20.
* Coverage                  : 67.7% (Partial).
* Omitted questions:
*   - AUTOQ1: Consent question terminates flow; single binary response, no macro check needed for validation logic beyond standard single-punch (no macro applies to simple consent)..
*   - AUTOQ2: Single binary terminate-logic screener question; no multi/rank/sum macro applies..
*   - AUTOQ3: Single binary terminate-logic screener question; no multi/rank/sum macro applies..
*   - AUTOQ5: Single binary consent-style question; no macro applies..
*   - PT10: Single binary pre-test availability question; no macro applies..
*   - PT20: Single binary pre-test consent question; no macro applies..
*   - AUTOQ6: Single-select specialty screener (variable s10); standard single-punch, no multi/sum/rank macro needed..
*   - AUTOQ7: Single-select board certification screener (variable s20); no macro applies..
*   - AUTOQ8: Single binary certification screener; no macro applies..
*   - AUTOQ10: Single-select country screener (variable s50); no macro applies..
*   - AUTOQ34: No matching dataset variables found for this trial-criterion age-group grid item; cannot confidently map SPSS variable naming.
*   - AUTOQ39: Single-select question (q260) with no numeric range/sum/rank logic suitable for standard macros; response is a categorical single choice already constrained by radio button UI..
*   - AUTOQ40: Single-select likelihood scale (q270_1), categorical radio, no macro applicable..
*   - AUTOQ43: Grid of single-select rating items (q300_1 to q300_5), each row is a single categorical choice with no sum/count/rank logic for macros..
*   - AUTOQ47: Single-select likelihood scale (q340_1), categorical radio, no macro applicable..
*   - AUTOQ50: Single-select likelihood scale (q370_1), categorical radio, no macro applicable..
*   - AUTOQ53: Single-select likelihood scale (q400_1), categorical radio, no macro applicable..
*   - AUTOQ56: Single-select question (q430) with categorical options (Yes/No/DK/Other); no macro applicable..
*   - AUTOQ58: Single-select 7-point receptivity scale (q450_1), categorical radio, no macro applicable..
*   - AUTOQ59: Open-ended text response (maps to Q460); no standard macro applies to free-text verbatim..

