* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-14T16:26:59.796997+00:00.
* Survey source: (V9 R98676) CRA-Astellas_Dravet_Syndrome_HCP_Survey_v28May2026.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AUTOQ1: no validation emitted - Consent question with terminate logic handled by routing, not a data-quality check candidate for standard macros.

* AUTOQ2: no validation emitted - Single yes/no gate question with terminate logic, no macro applicable.

* AUTOQ3: no validation emitted - Single yes/no gate question with terminate logic, no macro applicable.

* AUTOQ5: no validation emitted - Single yes/no consent-style question, no macro applicable.

* PT10: no validation emitted - Single yes/no pre-test availability question, no macro applicable.

* PT20: no validation emitted - Single yes/no pre-test consent question, no macro applicable.

***************************************AUTOQ6.
tit AUTOQ6 - S10 primary specialty not answered.
if(miss(s10)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s10 s10g_98_other.
DELETE VARIABLES flag.

***************************************AUTOQ7.
tit AUTOQ7 - S20 board certification not answered.
if(miss(s20)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s20.
DELETE VARIABLES flag.

***************************************AUTOQ8.
tit AUTOQ8 - S30 certification question not answered.
if(miss(s30)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s30.
DELETE VARIABLES flag.

***************************************AUTOQ9.
tit AUTOQ9 - Years in practice out of allowed range (0-100).
if(s40_1 < 0 or s40_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s40_1.
DELETE VARIABLES flag.

***************************************AUTOQ10.
tit AUTOQ10 - S50 country not answered.
if(miss(s50)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s50.
DELETE VARIABLES flag.

***************************************AUTOQ11.
!SUM_TO_VAR svar=s70_1 evar=s70_98 qnt=AUTOQ11 opr=<>.

***************************************AUTOQ12.
tit AUTOQ12 - S80 patient counts out of allowed range (0-100).
if(range(s80_1,s80_2,s80_3,s80_4,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_1 s80_2 s80_3 s80_4.
DELETE VARIABLES flag.

***************************************S85.
!SUM_TO_VAR svar=s85_1 evar=s85_5 qnt=S85 opr=<>.

***************************************AUTOQ13.
!MULTI_A svar=s90_1 evar=s90_98 qnt=AUTOQ13.

***************************************AUTOQ14.
tit AUTOQ14 - S100_1 not answered.
if(miss(s100_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_1.
DELETE VARIABLES flag.
tit AUTOQ14 - S100_2 not answered.
if(miss(s100_2)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_2.
DELETE VARIABLES flag.
tit AUTOQ14 - S100_3 not answered.
if(miss(s100_3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_3.
DELETE VARIABLES flag.

***************************************AUTOQ15.
!MULTI_B svar=q10_1 evar=q10_98 qnt=AUTOQ15.

***************************************AUTOQ16.
!SUM_TO_VAR svar=q20_1 evar=q20_2 qnt=AUTOQ16 opr=<>.

***************************************AUTOQ17.
tit AUTOQ17 - Q30 SCN1A mutation proportion out of range (0-100).
if(q30_1 < 0 or q30_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q30_1.
DELETE VARIABLES flag.

***************************************AUTOQ18.
!MULTI_A svar=q40_1 evar=q40_98 qnt=AUTOQ18.

***************************************AUTOQ19.
tit AUTOQ19 - Prevalence perception not answered.
if(miss(q50_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q50_1.
DELETE VARIABLES flag.

***************************************AUTOQ20.
tit AUTOQ20 - Diagnosed prevalence out of allowed range (1-100K).
if(q60x_1 < 1 or q60x_1 > 100000) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q60x_1.
DELETE VARIABLES flag.

***************************************AUTOQ21.
tit AUTOQ21 - Diagnosis rate change perception not answered.
if(miss(q70)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70.
DELETE VARIABLES flag.

***************************************AUTOQ22.
tit AUTOQ22 - Diagnosis rate increase % out of range 0-100 when Q70=3.
if(q70=3 and (q90_1 < 0 or q90_1 > 100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70 q90_1.
DELETE VARIABLES flag.
tit AUTOQ22 - Q90 missing when Q70=3 routing requires answer.
if(q70=3 and miss(q90_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70 q90_1.
DELETE VARIABLES flag.

***************************************AUTOQ23.
!SUM_TO_VAR svar=q100_1 evar=q100_3 qnt=AUTOQ23.

***************************************AUTOQ24.
!SUM_TO_VAR svar=q110_1 evar=q110_5 qnt=AUTOQ24.

***************************************AUTOQ25.
!MULTI_B svar=None evar=None qnt=AUTOQ25.
!MULTI_B svar=None evar=None qnt=AUTOQ25.
!MULTI_B svar=None evar=None qnt=AUTOQ25.
!MULTI_B svar=None evar=None qnt=AUTOQ25.
!MULTI_B svar=None evar=None qnt=AUTOQ25.

***************************************AUTOQ26.
!SUM_TO_VAR svar=q130x1_1 evar=q130x1_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x2_1 evar=q130x2_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x3_1 evar=q130x3_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x4_1 evar=q130x4_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x5_1 evar=q130x5_4 qnt=AUTOQ26.

***************************************AUTOQ27.
!MULTI_A svar=None evar=None qnt=AUTOQ27.

***************************************AUTOQ28.
tit AUTOQ28 - Seizure reduction % out of range 0-100.
if(q150_1 < 0 or q150_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q150_1.
DELETE VARIABLES flag.

***************************************AUTOQ29.
tit AUTOQ29 - Percentage not achieving good seizure control out of range 0-100.
if(q160_1 < 0 or q160_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q160_1.
DELETE VARIABLES flag.

***************************************AUTOQ30.
tit AUTOQ30 - Percentage considered for gene therapy out of range 0-100.
if(q170_1 < 0 or q170_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q170_1.
DELETE VARIABLES flag.

***************************************AUTOQ31.
tit AUTOQ31 - Open-ended initial thoughts on PRODUCT X not answered.
if(miss(q180)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q180.
DELETE VARIABLES flag.

***************************************AUTOQ32.
!MULTI_NUMB svar=None evar=None qnt=AUTOQ32.
!MULTI_B svar=None evar=None qnt=AUTOQ32.

***************************************AUTOQ33.
!MULTI_NUMB svar=None evar=None qnt=AUTOQ33.
!MULTI_B svar=None evar=None qnt=AUTOQ33.

***************************************AUTOQ34.

***************************************AUTOQ35.
tit AUTOQ35 - Likelihood to prescribe PRODUCT X not answered.
if(miss(q220_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q220_1.
DELETE VARIABLES flag.

***************************************AUTOQ36.
tit AUTOQ36 - Open-ended initial thoughts on PRODUCT Y not answered.
if(miss(q230)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q230.
DELETE VARIABLES flag.

***************************************AUTOQ37.
!MULTI_NUMB svar=None evar=None qnt=AUTOQ37.
!MULTI_B svar=None evar=None qnt=AUTOQ37.

***************************************AUTOQ38.
!MULTI_NUMB svar=None evar=None qnt=AUTOQ38.
!MULTI_B svar=None evar=None qnt=AUTOQ38.

***************************************AUTOQ39.
tit AUTOQ39 - Q260 (inpatient/outpatient setting) left blank.
if(miss(q260)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q260.
DELETE VARIABLES flag.

***************************************AUTOQ40.
tit AUTOQ40 - Q270_1 (likelihood to prescribe PRODUCT Y) left blank.
if(miss(q270_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q270_1.
DELETE VARIABLES flag.

***************************************AUTOQ41.
tit AUTOQ41 - Q280_1 out of range (0-100) or missing.
if(miss(q280_1) or q280_1<0 or q280_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q280_1.
DELETE VARIABLES flag.

***************************************AUTOQ42.
!SUM_TO_VAR svar=q290x1_1 evar=q290x5_1 qnt=AUTOQ42.

***************************************AUTOQ43.
tit AUTOQ43 - Q300 grid rows left blank.
if(miss(q300_1) or miss(q300_2) or miss(q300_3) or miss(q300_4) or miss(q300_5)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_1 q300_2 q300_3 q300_4 q300_5.
DELETE VARIABLES flag.

***************************************AUTOQ44.
!SUM_TO_VAR svar=q310x1_1 evar=q310x1_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x2_1 evar=q310x2_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x3_1 evar=q310x3_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x4_1 evar=q310x4_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x5_1 evar=q310x5_98 qnt=AUTOQ44.

***************************************AUTOQ45.
tit AUTOQ45 - Q320x1_1 switch proportion out of range 0-100.
if(q320x1_1<0 or q320x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x1_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x2_1 switch proportion out of range 0-100.
if(q320x2_1<0 or q320x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x2_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x3_1 switch proportion out of range 0-100.
if(q320x3_1<0 or q320x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x3_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x4_1 switch proportion out of range 0-100.
if(q320x4_1<0 or q320x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x4_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x5_1 switch proportion out of range 0-100.
if(q320x5_1<0 or q320x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ46.
!SUM_TO_VAR svar=q330x1_1 evar=q330x1_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x2_1 evar=q330x2_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x3_1 evar=q330x3_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x4_1 evar=q330x4_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x5_1 evar=q330x5_98 qnt=AUTOQ46.

***************************************AUTOQ47.
tit AUTOQ47 - Q340_1 (likelihood to prescribe PRODUCT Y variation #1) left blank.
if(miss(q340_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q340_1.
DELETE VARIABLES flag.

***************************************AUTOQ48.
tit AUTOQ48 - Q350x1_1 switch proportion out of range 0-100.
if(q350x1_1<0 or q350x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x1_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x2_1 switch proportion out of range 0-100.
if(q350x2_1<0 or q350x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x2_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x3_1 switch proportion out of range 0-100.
if(q350x3_1<0 or q350x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x3_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x4_1 switch proportion out of range 0-100.
if(q350x4_1<0 or q350x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x4_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x5_1 switch proportion out of range 0-100.
if(q350x5_1<0 or q350x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ49.
!SUM_TO_VAR svar=q360x1_1 evar=q360x1_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x2_1 evar=q360x2_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x3_1 evar=q360x3_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x4_1 evar=q360x4_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x5_1 evar=q360x5_98 qnt=AUTOQ49.

***************************************AUTOQ50.
tit AUTOQ50 - Q370_1 (likelihood to prescribe PRODUCT Y variation #2) left blank.
if(miss(q370_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q370_1.
DELETE VARIABLES flag.

***************************************AUTOQ51.
tit AUTOQ51 - Q380x1_1 switch proportion out of range 0-100.
if(q380x1_1<0 or q380x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x1_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x2_1 switch proportion out of range 0-100.
if(q380x2_1<0 or q380x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x2_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x3_1 switch proportion out of range 0-100.
if(q380x3_1<0 or q380x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x3_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x4_1 switch proportion out of range 0-100.
if(q380x4_1<0 or q380x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x4_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x5_1 switch proportion out of range 0-100.
if(q380x5_1<0 or q380x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ52.
!SUM_TO_VAR svar=q390x1_1 evar=q390x1_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x2_1 evar=q390x2_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x3_1 evar=q390x3_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x4_1 evar=q390x4_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x5_1 evar=q390x5_98 qnt=AUTOQ52.

***************************************AUTOQ53.
tit AUTOQ53 - Q400_1 (likelihood to prescribe PRODUCT Y variation #3) left blank.
if(miss(q400_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q400_1.
DELETE VARIABLES flag.

***************************************AUTOQ54.
tit AUTOQ54 - Q410x1_1 switch proportion out of range 0-100.
if(q410x1_1<0 or q410x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x1_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x2_1 switch proportion out of range 0-100.
if(q410x2_1<0 or q410x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x2_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x3_1 switch proportion out of range 0-100.
if(q410x3_1<0 or q410x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x3_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x4_1 switch proportion out of range 0-100.
if(q410x4_1<0 or q410x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x4_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x5_1 switch proportion out of range 0-100.
if(q410x5_1<0 or q410x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ55.
!SUM_TO_VAR svar=q420x1_1 evar=q420x1_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x2_1 evar=q420x2_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x3_1 evar=q420x3_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x4_1 evar=q420x4_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x5_1 evar=q420x5_98 qnt=AUTOQ55.

***************************************AUTOQ56.
tit AUTOQ56 - Q430 (institution ICV capability) left blank.
if(miss(q430)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430.
DELETE VARIABLES flag.

***************************************AUTOQ57.
tit AUTOQ57 - Q440_1 out of range (0-60) or missing when Q430=Yes.
if(q430=1 and (miss(q440_1) or q440_1<0 or q440_1>60)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q440_1.
DELETE VARIABLES flag.

***************************************AUTOQ58.
tit AUTOQ58 - Q450_1 receptiveness left blank when Q430=Yes.
if(q430=1 and miss(q450_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q450_1.
DELETE VARIABLES flag.

* AUTOQ59: no validation emitted - Open-ended text response (maps to q460); no standard macro applies to free-text verbatim..

***************************************AUTOQ60.
tit AUTOQ60 - Months for Product X out of allowed range 0-60 or missing.
if(miss(q470_1) or range(q470_1,0,60)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q470_1.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 62.
* Checks emitted            : 105.
* Questions omitted         : 8.
* Coverage                  : 87.1% (Partial).
* Omitted questions:
*   - AUTOQ1: Consent question with terminate logic handled by routing, not a data-quality check candidate for standard macros.
*   - AUTOQ2: Single yes/no gate question with terminate logic, no macro applicable.
*   - AUTOQ3: Single yes/no gate question with terminate logic, no macro applicable.
*   - AUTOQ5: Single yes/no consent-style question, no macro applicable.
*   - PT10: Single yes/no pre-test availability question, no macro applicable.
*   - PT20: Single yes/no pre-test consent question, no macro applicable.
*   - AUTOQ34: Grid item wording and variable mapping unclear (age-group conditional piping, no exact SPSS variable dictionary match found for this trial-criterion percentage grid); cannot confidently infer variable names.
*   - AUTOQ59: Open-ended text response (maps to q460); no standard macro applies to free-text verbatim..

