* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-14T16:43:06.796941+00:00.
* Survey source: (V9 R98676) CRA-Astellas_Dravet_Syndrome_HCP_Survey_v28May2026.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AUTOQ1: no validation emitted - Consent single-punch terminate question; no macro validation needed, routing/terminate only..

* AUTOQ2: no validation emitted - Yes/No terminate gate question; no macro validation needed..

* AUTOQ3: no validation emitted - Yes/No terminate gate question; no macro validation needed..

* AUTOQ5: no validation emitted - Single Yes/No consent-style question; no macro validation needed..

* PT10: no validation emitted - Single Yes/No pre-test gate question; no macro validation needed..

* PT20: no validation emitted - Single Yes/No pre-test gate question; no macro validation needed..

* AUTOQ6: no validation emitted - Single-select specialty screener question (variable s10); not a grid battery requiring range validation, and single categorical selection needs no macro check..

* AUTOQ7: no validation emitted - Single-select board certification screener question (variable s20); no macro validation needed..

* AUTOQ8: no validation emitted - Single Yes/No certification screener question; no macro validation needed..

***************************************AUTOQ9.
tit AUTOQ9 - Years in practice outside terminate range (3-35) - verify termination logic.
if(range(s40_1,3,35) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s40_1.
DELETE VARIABLES flag.

* AUTOQ10: no validation emitted - Single-select country screener question (variable s50); no macro validation needed..

***************************************AUTOQ11.
tit AUTOQ11 - S70 time allocation percentages do not sum to 100.
if(sum(s70_1,s70_2,s70_3,s70_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s70_1 s70_2 s70_3 s70_98.
DELETE VARIABLES flag.

***************************************AUTOQ12.
tit AUTOQ12 - S80_1 SMD patient count out of allowed range 0-100.
if(range(s80_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_1.
DELETE VARIABLES flag.
tit AUTOQ12 - S80_2 LGS patient count out of allowed range 0-100.
if(range(s80_2,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_2.
DELETE VARIABLES flag.
tit AUTOQ12 - S80_3 Dravet patient count out of allowed range 0-100.
if(range(s80_3,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_3.
DELETE VARIABLES flag.
tit AUTOQ12 - S80_4 Rett patient count out of allowed range 0-100.
if(range(s80_4,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_4.
DELETE VARIABLES flag.

***************************************S85.
tit S85 - S85 age group percentages do not sum to 100.
if(sum(s85_1,s85_2,s85_3,s85_4,s85_5) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s85_1 s85_2 s85_3 s85_4 s85_5.
DELETE VARIABLES flag.

***************************************AUTOQ13.
!MULTI_A svar=s90_1 evar=s90_98 qnt=AUTOQ13.

* AUTOQ14: no validation emitted - Battery of three Yes/No screener eligibility questions (s100_1-3); each is a simple terminate-style single response, no macro validation applicable..

***************************************AUTOQ15.
!MULTI_B svar=q10_1 evar=q10dk_99 qnt=AUTOQ15.
tit AUTOQ15 - Q10 insurance coverage percentages do not sum to 100 (when DK not selected).
if(sum(q10_1,q10_2,q10_3,q10_4,q10_98) <> 100 and q10dk_99 = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q10_1 q10_2 q10_3 q10_4 q10_98 q10dk_99.
DELETE VARIABLES flag.

***************************************AUTOQ16.
tit AUTOQ16 - Q20 diagnosis source percentages do not sum to 100.
if(sum(q20_1,q20_2) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q20_1 q20_2.
DELETE VARIABLES flag.

***************************************AUTOQ17.
tit AUTOQ17 - Q30_1 SCN1A confirmed mutation proportion out of range 0-100.
if(range(q30_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q30_1.
DELETE VARIABLES flag.

***************************************AUTOQ18.
!MULTI_A svar=q40_1 evar=q40_98 qnt=AUTOQ18.

***************************************AUTOQ19.
tit AUTOQ19 - Prevalence perception not answered.
if(miss(q50_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q50_1.
DELETE VARIABLES flag.

***************************************AUTOQ20.
tit AUTOQ20 - Diagnosed prevalence out of range (1-100K).
if(miss(q60x_1) or q60x_1<1 or q60x_1>100000) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q60x_1.
DELETE VARIABLES flag.

***************************************AUTOQ21.
tit AUTOQ21 - Diagnosis rate change not answered.
if(miss(q70)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70.
DELETE VARIABLES flag.

***************************************AUTOQ22.
tit AUTOQ22 - Diagnosis rate increase % missing or out of range when Q70=3.
if(q70=3 and (miss(q90_1) or q90_1<0 or q90_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70 q90_1.
DELETE VARIABLES flag.

***************************************AUTOQ23.
!SUM_TO_VAR svar=q100_1 evar=q100_3 qnt=AUTOQ23.

***************************************AUTOQ24.
!SUM_TO_VAR svar=q110_1 evar=q110_5 qnt=AUTOQ24.

***************************************AUTOQ25.
!MULTI_B svar=q120x1_1 evar=q120x1_99 qnt=AUTOQ25.
!MULTI_B svar=q120x2_1 evar=q120x2_99 qnt=AUTOQ25.
!MULTI_B svar=q120x3_1 evar=q120x3_99 qnt=AUTOQ25.
!MULTI_B svar=q120x4_1 evar=q120x4_99 qnt=AUTOQ25.
!MULTI_B svar=q120x5_1 evar=q120x5_99 qnt=AUTOQ25.

***************************************AUTOQ26.
!SUM_TO_VAR svar=q130x1_1 evar=q130x1_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x2_1 evar=q130x2_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x3_1 evar=q130x3_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x4_1 evar=q130x4_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x5_1 evar=q130x5_4 qnt=AUTOQ26.

***************************************AUTOQ27.
!MULTI_A svar=q140_1 evar=q140_98 qnt=AUTOQ27.

***************************************AUTOQ28.
tit AUTOQ28 - Good seizure control threshold % missing or out of range.
if(miss(q150_1) or q150_1<0 or q150_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q150_1.
DELETE VARIABLES flag.

***************************************AUTOQ29.
tit AUTOQ29 - % not achieving good seizure control missing or out of range.
if(miss(q160_1) or q160_1<0 or q160_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q160_1.
DELETE VARIABLES flag.

***************************************AUTOQ30.
tit AUTOQ30 - % considered for gene therapy missing or out of range.
if(miss(q170_1) or q170_1<0 or q170_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q170_1.
DELETE VARIABLES flag.

***************************************AUTOQ31.
tit AUTOQ31 - Initial thoughts on PRODUCT X not answered.
if(miss(q180)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q180.
DELETE VARIABLES flag.

***************************************AUTOQ32.
!MULTI_NUMB svar=q190_1 evar=q190_98 qnt=AUTOQ32.
tit AUTOQ32 - No advantages option selected alongside substantive advantage codes.
if(q190_99=1 and (sum(q190_1,q190_2,q190_3,q190_4,q190_5,q190_6,q190_7,q190_8)>0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q190_99 q190_1 q190_2 q190_3 q190_4 q190_5 q190_6 q190_7 q190_8.
DELETE VARIABLES flag.

***************************************AUTOQ33.
!MULTI_NUMB svar=q200_1 evar=q200_98 qnt=AUTOQ33.
tit AUTOQ33 - No disadvantages option selected alongside substantive disadvantage codes.
if(q200_99=1 and (sum(q200_1,q200_2,q200_3,q200_4,q200_5,q200_6,q200_7,q200_8)>0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q200_99 q200_1 q200_2 q200_3 q200_4 q200_5 q200_6 q200_7 q200_8.
DELETE VARIABLES flag.

***************************************AUTOQ34.
tit AUTOQ34 - Trial criteria % missing or out of range for <2 years when Q110_1>0.
if(q110_1>0 and (miss(q210x1_1) or q210x1_1<0 or q210x1_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q110_1 q210x1_1.
DELETE VARIABLES flag.
tit AUTOQ34 - Trial criteria % missing or out of range for 2 to <4 years when Q110_2>0.
if(q110_2>0 and (miss(q210x2_1) or q210x2_1<0 or q210x2_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q110_2 q210x2_1.
DELETE VARIABLES flag.
tit AUTOQ34 - Trial criteria % missing or out of range for 4 to <12 years when Q110_3>0.
if(q110_3>0 and (miss(q210x3_1) or q210x3_1<0 or q210x3_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q110_3 q210x3_1.
DELETE VARIABLES flag.
tit AUTOQ34 - Trial criteria % missing or out of range for 12 to <18 years when Q110_4>0.
if(q110_4>0 and (miss(q210x4_1) or q210x4_1<0 or q210x4_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q110_4 q210x4_1.
DELETE VARIABLES flag.
tit AUTOQ34 - Trial criteria % missing or out of range for 18+ years when Q110_5>0.
if(q110_5>0 and (miss(q210x5_1) or q210x5_1<0 or q210x5_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q110_5 q210x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ35.
tit AUTOQ35 - Likelihood to prescribe PRODUCT X not answered.
if(miss(q220_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q220_1.
DELETE VARIABLES flag.

***************************************AUTOQ36.
tit AUTOQ36 - Initial thoughts on PRODUCT Y not answered.
if(miss(q230)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q230.
DELETE VARIABLES flag.

***************************************AUTOQ37.
!MULTI_NUMB svar=q240_1 evar=q240_98 qnt=AUTOQ37.
tit AUTOQ37 - No advantages option selected alongside substantive advantage codes.
if(q240_13=1 and (sum(q240_1,q240_2,q240_3,q240_4,q240_5,q240_6,q240_7,q240_8,q240_9,q240_10,q240_11,q240_12)>0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q240_13 q240_1 q240_2 q240_3 q240_4 q240_5 q240_6 q240_7 q240_8 q240_9 q240_10 q240_11 q240_12.
DELETE VARIABLES flag.

***************************************AUTOQ38.
!MULTI_NUMB svar=q250_1 evar=q250_98 qnt=AUTOQ38.
tit AUTOQ38 - No disadvantages option selected alongside substantive disadvantage codes.
if(q250_13=1 and (sum(q250_1,q250_2,q250_3,q250_4,q250_5,q250_6,q250_7,q250_8,q250_9,q250_10,q250_11,q250_12)>0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q250_13 q250_1 q250_2 q250_3 q250_4 q250_5 q250_6 q250_7 q250_8 q250_9 q250_10 q250_11 q250_12.
DELETE VARIABLES flag.

***************************************AUTOQ39.
tit AUTOQ39 - Q260 (inpatient/outpatient setting) not answered.
if(miss(q260)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q260.
DELETE VARIABLES flag.

***************************************AUTOQ40.
tit AUTOQ40 - Q270_1 likelihood to prescribe Product Y not answered.
if(miss(q270_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q270_1.
DELETE VARIABLES flag.

***************************************AUTOQ41.
tit AUTOQ41 - Q280_1 age response missing or out of range 0-100.
if(miss(q280_1) or range(q280_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q280_1.
DELETE VARIABLES flag.

***************************************AUTOQ42.
tit AUTOQ42 - Q290 age distribution grid entirely missing.
if(miss(q290x1_1) and miss(q290x2_1) and miss(q290x3_1) and miss(q290x4_1) and miss(q290x5_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q290x1_1 q290x2_1 q290x3_1 q290x4_1 q290x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ43.
tit AUTOQ43 - Q300 motivation grid incomplete (not all rows answered).
if(nvalid(q300_1,q300_2,q300_3,q300_4,q300_5) < 5) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_1 q300_2 q300_3 q300_4 q300_5.
DELETE VARIABLES flag.

***************************************AUTOQ44.
tit AUTOQ44 - Q310x1 (<2 years) row does not sum to 100.
if(sum(q310x1_1,q310x1_2,q310x1_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310x1_1 q310x1_2 q310x1_98.
DELETE VARIABLES flag.
tit AUTOQ44 - Q310x2 (2 to <4 years) row does not sum to 100.
if(sum(q310x2_1,q310x2_2,q310x2_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310x2_1 q310x2_2 q310x2_98.
DELETE VARIABLES flag.
tit AUTOQ44 - Q310x3 (4 to <12 years) row does not sum to 100.
if(sum(q310x3_1,q310x3_2,q310x3_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310x3_1 q310x3_2 q310x3_98.
DELETE VARIABLES flag.
tit AUTOQ44 - Q310x4 (12 to <18 years) row does not sum to 100.
if(sum(q310x4_1,q310x4_2,q310x4_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310x4_1 q310x4_2 q310x4_98.
DELETE VARIABLES flag.
tit AUTOQ44 - Q310x5 (18+ years) row does not sum to 100.
if(sum(q310x5_1,q310x5_2,q310x5_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310x5_1 q310x5_2 q310x5_98.
DELETE VARIABLES flag.

***************************************AUTOQ45.
tit AUTOQ45 - Q320x1_1 switch proportion out of range 0-100.
if(range(q320x1_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x1_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x2_1 switch proportion out of range 0-100.
if(range(q320x2_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x2_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x3_1 switch proportion out of range 0-100.
if(range(q320x3_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x3_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x4_1 switch proportion out of range 0-100.
if(range(q320x4_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x4_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x5_1 switch proportion out of range 0-100.
if(range(q320x5_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ46.
tit AUTOQ46 - Q330x1 (<2 years) row does not sum to 100.
if(sum(q330x1_1,q330x1_2,q330x1_3,q330x1_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q330x1_1 q330x1_2 q330x1_3 q330x1_98.
DELETE VARIABLES flag.
tit AUTOQ46 - Q330x2 (2 to <4 years) row does not sum to 100.
if(sum(q330x2_1,q330x2_2,q330x2_3,q330x2_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q330x2_1 q330x2_2 q330x2_3 q330x2_98.
DELETE VARIABLES flag.
tit AUTOQ46 - Q330x3 (4 to <12 years) row does not sum to 100.
if(sum(q330x3_1,q330x3_2,q330x3_3,q330x3_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q330x3_1 q330x3_2 q330x3_3 q330x3_98.
DELETE VARIABLES flag.
tit AUTOQ46 - Q330x4 (12 to <18 years) row does not sum to 100.
if(sum(q330x4_1,q330x4_2,q330x4_3,q330x4_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q330x4_1 q330x4_2 q330x4_3 q330x4_98.
DELETE VARIABLES flag.
tit AUTOQ46 - Q330x5 (18+ years) row does not sum to 100.
if(sum(q330x5_1,q330x5_2,q330x5_3,q330x5_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q330x5_1 q330x5_2 q330x5_3 q330x5_98.
DELETE VARIABLES flag.

***************************************AUTOQ47.
tit AUTOQ47 - Q340_1 likelihood to prescribe Product Y variation #1 not answered.
if(miss(q340_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q340_1.
DELETE VARIABLES flag.

***************************************AUTOQ48.
tit AUTOQ48 - Q350x1_1 switch proportion out of range 0-100.
if(range(q350x1_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x1_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x2_1 switch proportion out of range 0-100.
if(range(q350x2_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x2_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x3_1 switch proportion out of range 0-100.
if(range(q350x3_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x3_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x4_1 switch proportion out of range 0-100.
if(range(q350x4_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x4_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x5_1 switch proportion out of range 0-100.
if(range(q350x5_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ49.
tit AUTOQ49 - Q360x1 (<2 years) row does not sum to 100.
if(sum(q360x1_1,q360x1_2,q360x1_3,q360x1_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q360x1_1 q360x1_2 q360x1_3 q360x1_98.
DELETE VARIABLES flag.
tit AUTOQ49 - Q360x2 (2 to <4 years) row does not sum to 100.
if(sum(q360x2_1,q360x2_2,q360x2_3,q360x2_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q360x2_1 q360x2_2 q360x2_3 q360x2_98.
DELETE VARIABLES flag.
tit AUTOQ49 - Q360x3 (4 to <12 years) row does not sum to 100.
if(sum(q360x3_1,q360x3_2,q360x3_3,q360x3_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q360x3_1 q360x3_2 q360x3_3 q360x3_98.
DELETE VARIABLES flag.
tit AUTOQ49 - Q360x4 (12 to <18 years) row does not sum to 100.
if(sum(q360x4_1,q360x4_2,q360x4_3,q360x4_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q360x4_1 q360x4_2 q360x4_3 q360x4_98.
DELETE VARIABLES flag.
tit AUTOQ49 - Q360x5 (18+ years) row does not sum to 100.
if(sum(q360x5_1,q360x5_2,q360x5_3,q360x5_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q360x5_1 q360x5_2 q360x5_3 q360x5_98.
DELETE VARIABLES flag.

***************************************AUTOQ50.
tit AUTOQ50 - Q370_1 likelihood to prescribe Product Y variation #2 not answered.
if(miss(q370_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q370_1.
DELETE VARIABLES flag.

***************************************AUTOQ51.
tit AUTOQ51 - Q380x1_1 switch proportion out of range 0-100.
if(range(q380x1_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x1_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x2_1 switch proportion out of range 0-100.
if(range(q380x2_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x2_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x3_1 switch proportion out of range 0-100.
if(range(q380x3_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x3_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x4_1 switch proportion out of range 0-100.
if(range(q380x4_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x4_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x5_1 switch proportion out of range 0-100.
if(range(q380x5_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ52.
tit AUTOQ52 - Q390x1 (<2 years) row does not sum to 100.
if(sum(q390x1_1,q390x1_2,q390x1_3,q390x1_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q390x1_1 q390x1_2 q390x1_3 q390x1_98.
DELETE VARIABLES flag.
tit AUTOQ52 - Q390x2 (2 to <4 years) row does not sum to 100.
if(sum(q390x2_1,q390x2_2,q390x2_3,q390x2_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q390x2_1 q390x2_2 q390x2_3 q390x2_98.
DELETE VARIABLES flag.
tit AUTOQ52 - Q390x3 (4 to <12 years) row does not sum to 100.
if(sum(q390x3_1,q390x3_2,q390x3_3,q390x3_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q390x3_1 q390x3_2 q390x3_3 q390x3_98.
DELETE VARIABLES flag.
tit AUTOQ52 - Q390x4 (12 to <18 years) row does not sum to 100.
if(sum(q390x4_1,q390x4_2,q390x4_3,q390x4_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q390x4_1 q390x4_2 q390x4_3 q390x4_98.
DELETE VARIABLES flag.
tit AUTOQ52 - Q390x5 (18+ years) row does not sum to 100.
if(sum(q390x5_1,q390x5_2,q390x5_3,q390x5_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q390x5_1 q390x5_2 q390x5_3 q390x5_98.
DELETE VARIABLES flag.

***************************************AUTOQ53.
tit AUTOQ53 - Q400_1 likelihood to prescribe Product Y variation #3 not answered.
if(miss(q400_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q400_1.
DELETE VARIABLES flag.

***************************************AUTOQ54.
tit AUTOQ54 - Q410x1_1 switch proportion out of range 0-100.
if(range(q410x1_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x1_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x2_1 switch proportion out of range 0-100.
if(range(q410x2_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x2_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x3_1 switch proportion out of range 0-100.
if(range(q410x3_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x3_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x4_1 switch proportion out of range 0-100.
if(range(q410x4_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x4_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x5_1 switch proportion out of range 0-100.
if(range(q410x5_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ55.
tit AUTOQ55 - Q420x1 (<2 years) row does not sum to 100.
if(sum(q420x1_1,q420x1_2,q420x1_3,q420x1_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q420x1_1 q420x1_2 q420x1_3 q420x1_98.
DELETE VARIABLES flag.
tit AUTOQ55 - Q420x2 (2 to <4 years) row does not sum to 100.
if(sum(q420x2_1,q420x2_2,q420x2_3,q420x2_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q420x2_1 q420x2_2 q420x2_3 q420x2_98.
DELETE VARIABLES flag.
tit AUTOQ55 - Q420x3 (4 to <12 years) row does not sum to 100.
if(sum(q420x3_1,q420x3_2,q420x3_3,q420x3_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q420x3_1 q420x3_2 q420x3_3 q420x3_98.
DELETE VARIABLES flag.
tit AUTOQ55 - Q420x4 (12 to <18 years) row does not sum to 100.
if(sum(q420x4_1,q420x4_2,q420x4_3,q420x4_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q420x4_1 q420x4_2 q420x4_3 q420x4_98.
DELETE VARIABLES flag.
tit AUTOQ55 - Q420x5 (18+ years) row does not sum to 100.
if(sum(q420x5_1,q420x5_2,q420x5_3,q420x5_98) <> 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q420x5_1 q420x5_2 q420x5_3 q420x5_98.
DELETE VARIABLES flag.

***************************************AUTOQ56.
tit AUTOQ56 - Q430 institution ICV capability question not answered.
if(miss(q430)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430.
DELETE VARIABLES flag.

***************************************AUTOQ57.
tit AUTOQ57 - Q440_1 implementation time missing or out of range 0-60 when Q430=Yes.
if(q430=1 and (miss(q440_1) or range(q440_1,0,60)=0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q440_1.
DELETE VARIABLES flag.

***************************************AUTOQ58.
tit AUTOQ58 - Q450_1 institution receptiveness not answered when Q430=Yes.
if(q430=1 and miss(q450_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q450_1.
DELETE VARIABLES flag.

* AUTOQ59: no validation emitted - Open-ended text response (maps to q460); no standard macro applies to free-text verbatim..

***************************************AUTOQ60.
tit AUTOQ60 - Months for Product X out of allowed range (0-60).
if(not(range(q470_1,0,60))) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q470_1.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 62.
* Checks emitted            : 106.
* Questions omitted         : 12.
* Coverage                  : 80.6% (Partial).
* Omitted questions:
*   - AUTOQ1: Consent single-punch terminate question; no macro validation needed, routing/terminate only..
*   - AUTOQ2: Yes/No terminate gate question; no macro validation needed..
*   - AUTOQ3: Yes/No terminate gate question; no macro validation needed..
*   - AUTOQ5: Single Yes/No consent-style question; no macro validation needed..
*   - PT10: Single Yes/No pre-test gate question; no macro validation needed..
*   - PT20: Single Yes/No pre-test gate question; no macro validation needed..
*   - AUTOQ6: Single-select specialty screener question (variable s10); not a grid battery requiring range validation, and single categorical selection needs no macro check..
*   - AUTOQ7: Single-select board certification screener question (variable s20); no macro validation needed..
*   - AUTOQ8: Single Yes/No certification screener question; no macro validation needed..
*   - AUTOQ10: Single-select country screener question (variable s50); no macro validation needed..
*   - AUTOQ14: Battery of three Yes/No screener eligibility questions (s100_1-3); each is a simple terminate-style single response, no macro validation applicable..
*   - AUTOQ59: Open-ended text response (maps to q460); no standard macro applies to free-text verbatim..

