* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-16T09:33:59.238899+00:00.
* Survey source: (V9 R98676) CRA-Astellas_Dravet_Syndrome_HCP_Survey_v28May2026.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AUTOQ1: no validation emitted - Consent gate single-punch with terminate logic; no substantive data validation needed beyond routing..

* AUTOQ2: no validation emitted - Screener gate single-punch with terminate logic; no substantive data validation needed..

* AUTOQ3: no validation emitted - Screener gate single-punch with terminate logic; no substantive data validation needed..

* AUTOQ5: no validation emitted - Consent-style single-punch gate question; no substantive data validation needed..

* PT10: no validation emitted - Pre-test recruitment gate question with terminate logic; no substantive data validation needed..

* PT20: no validation emitted - Pre-test recruitment gate question with terminate logic; no substantive data validation needed..

***************************************AUTOQ6.
tit AUTOQ6 - S10 primary specialty not answered.
if(miss(s10)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s10.
DELETE VARIABLES flag.

***************************************AUTOQ7.
tit AUTOQ7 - S20 board certification not answered.
if(miss(s20)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s20.
DELETE VARIABLES flag.

***************************************AUTOQ8.
tit AUTOQ8 - S30 certification question not answered.
if(miss(s30)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s30.
DELETE VARIABLES flag.

***************************************AUTOQ9.
tit AUTOQ9 - S40_1 years in practice out of allowed range 0-100.
if(s40_1 < 0 or s40_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s40_1.
DELETE VARIABLES flag.

***************************************AUTOQ10.
tit AUTOQ10 - S50 country not answered.
if(miss(s50)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s50.
DELETE VARIABLES flag.

***************************************AUTOQ11.
!SUM_TO_VAR svar=s70_1 evar=s70_98 qnt=AUTOQ11 opr==.
tit AUTOQ11 - S70_1 clinical time out of 0-100 range.
if(range(s70_1,s70_98) and (s70_1<0 or s70_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s70_1.
DELETE VARIABLES flag.

***************************************AUTOQ12.
tit AUTOQ12 - S80_1 SMA patient count out of range.
if(s80_1<0 or s80_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_1.
DELETE VARIABLES flag.
tit AUTOQ12 - S80_2 LGS patient count out of range.
if(s80_2<0 or s80_2>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_2.
DELETE VARIABLES flag.
tit AUTOQ12 - S80_3 Dravet patient count out of range.
if(s80_3<0 or s80_3>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_3.
DELETE VARIABLES flag.
tit AUTOQ12 - S80_4 Rett patient count out of range.
if(s80_4<0 or s80_4>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s80_4.
DELETE VARIABLES flag.

***************************************S85.
!SUM_TO_VAR svar=s85_1 evar=s85_5 qnt=S85 opr==.

***************************************AUTOQ13.
!MULTI_A svar=s90_1 evar=s90_98 qnt=AUTOQ13.

***************************************AUTOQ14.
tit AUTOQ14 - S100_1 not answered.
if(miss(s100_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_1.
DELETE VARIABLES flag.
tit AUTOQ14 - S100_2 not answered.
if(miss(s100_2)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_2.
DELETE VARIABLES flag.
tit AUTOQ14 - S100_3 not answered.
if(miss(s100_3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s100_3.
DELETE VARIABLES flag.

***************************************AUTOQ15.
!SUM_TO_VAR svar=q10_1 evar=q10_98 qnt=AUTOQ15 opr==.
tit AUTOQ15 - Q10DK selected alongside substantive insurance percentages.
if(q10dk_99=1 and (sum(q10_1,q10_98)>0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q10dk_99 q10_1 q10_2 q10_3 q10_4 q10_98.
DELETE VARIABLES flag.

***************************************AUTOQ16.
!SUM_TO_VAR svar=q20_1 evar=q20_2 qnt=AUTOQ16 opr==.

***************************************AUTOQ17.
tit AUTOQ17 - Q30_1 SCN1A mutation proportion out of range.
if(q30_1<0 or q30_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q30_1.
DELETE VARIABLES flag.

***************************************AUTOQ18.
!MULTI_A svar=q40_1 evar=q40_98 qnt=AUTOQ18.

***************************************AUTOQ19.
tit AUTOQ19 - Perception of prevalence estimate not answered.
if(miss(q50_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q50_1.
DELETE VARIABLES flag.

***************************************AUTOQ20.
tit AUTOQ20 - Diagnosed prevalence out of allowed range (1-100K) or missing.
if(miss(q60x_1) or q60x_1<1 or q60x_1>100000) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q60x_1.
DELETE VARIABLES flag.

***************************************AUTOQ21.
tit AUTOQ21 - Diagnosis rate change perception not answered.
if(miss(q70)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70.
DELETE VARIABLES flag.

***************************************AUTOQ22.
tit AUTOQ22 - Expected diagnosis rate increase % missing or out of range 0-100 when Q70=3.
if(q70=3 and (miss(q90_1) or q90_1<0 or q90_1>100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70 q90_1.
DELETE VARIABLES flag.

***************************************AUTOQ23.
!SUM_TO_VAR svar=q100_1 evar=q100_3 qnt=AUTOQ23.

***************************************AUTOQ24.
!SUM_TO_VAR svar=q110_1 evar=q110_5 qnt=AUTOQ24.

***************************************AUTOQ25.
!MULTI_B svar=q120x1_1 evar=q120x1_98 qnt=AUTOQ25.
!MULTI_B svar=q120x2_1 evar=q120x2_98 qnt=AUTOQ25.
!MULTI_B svar=q120x3_1 evar=q120x3_98 qnt=AUTOQ25.
!MULTI_B svar=q120x4_1 evar=q120x4_98 qnt=AUTOQ25.
!MULTI_B svar=q120x5_1 evar=q120x5_98 qnt=AUTOQ25.

***************************************AUTOQ26.
!SUM_TO_VAR svar=q130x1_1 evar=q130x1_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x2_1 evar=q130x2_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x3_1 evar=q130x3_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x4_1 evar=q130x4_4 qnt=AUTOQ26.
!SUM_TO_VAR svar=q130x5_1 evar=q130x5_4 qnt=AUTOQ26.

***************************************AUTOQ27.
!MULTI_A svar=q140_1 evar=q140_98 qnt=AUTOQ27.

***************************************AUTOQ28.
tit AUTOQ28 - Seizure control reduction % missing or out of range 0-100.
if(miss(q150_1) or q150_1<0 or q150_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q150_1.
DELETE VARIABLES flag.

***************************************AUTOQ29.
tit AUTOQ29 - % second-line patients not achieving control missing or out of range 0-100.
if(miss(q160_1) or q160_1<0 or q160_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q160_1.
DELETE VARIABLES flag.

***************************************AUTOQ30.
tit AUTOQ30 - % patients considered for gene therapy missing or out of range 0-100.
if(miss(q170_1) or q170_1<0 or q170_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q170_1.
DELETE VARIABLES flag.

***************************************AUTOQ31.
tit AUTOQ31 - Initial thoughts on PRODUCT X not answered (open-end).
if(miss(q180)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q180.
DELETE VARIABLES flag.

***************************************AUTOQ32.
!MULTI_NUMB svar=q190_1 evar=q190_98 qnt=AUTOQ32.
!MULTI_B svar=q190_1 evar=q190_98 qnt=AUTOQ32.

***************************************AUTOQ33.
!MULTI_NUMB svar=q200_1 evar=q200_98 qnt=AUTOQ33.
!MULTI_B svar=q200_1 evar=q200_98 qnt=AUTOQ33.

* AUTOQ34: no validation emitted - Grid item naming for this age-group percentage breakdown could not be confidently mapped to dictionary variables (no matching Q34-style variables found); skipping to avoid guessing..

***************************************AUTOQ35.
tit AUTOQ35 - Likelihood to prescribe PRODUCT X not answered.
if(miss(q220_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q220_1.
DELETE VARIABLES flag.

***************************************AUTOQ36.
tit AUTOQ36 - Initial thoughts on PRODUCT Y not answered (open-end).
if(miss(q230)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q230.
DELETE VARIABLES flag.

***************************************AUTOQ37.
!MULTI_NUMB svar=q240_1 evar=q240_98 qnt=AUTOQ37.
!MULTI_B svar=q240_1 evar=q240_98 qnt=AUTOQ37.

***************************************AUTOQ38.
!MULTI_NUMB svar=q250_1 evar=q250_98 qnt=AUTOQ38.
!MULTI_B svar=q250_1 evar=q250_98 qnt=AUTOQ38.

* AUTOQ39: no validation emitted - Single-select categorical item (Q260); maps to q260 single variable, no range/sum/multi macro applicable - value range check not part of standard macro set.

***************************************AUTOQ40.
tit AUTOQ40 - Likelihood to prescribe PRODUCT Y not answered.
if(miss(q270_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q270_1.
DELETE VARIABLES flag.

***************************************AUTOQ41.
tit AUTOQ41 - Age out of allowed range 0-100.
if(q280_1 < 0 or q280_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q280_1.
DELETE VARIABLES flag.

***************************************AUTOQ42.
!SUM_TO_VAR svar=q290x1_1 evar=q290x5_1 qnt=AUTOQ42.

***************************************AUTOQ43.
tit AUTOQ43 - Q300_1 motivation not answered.
if(miss(q300_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_1.
DELETE VARIABLES flag.
tit AUTOQ43 - Q300_2 motivation not answered.
if(miss(q300_2)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_2.
DELETE VARIABLES flag.
tit AUTOQ43 - Q300_3 motivation not answered.
if(miss(q300_3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_3.
DELETE VARIABLES flag.
tit AUTOQ43 - Q300_4 motivation not answered.
if(miss(q300_4)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_4.
DELETE VARIABLES flag.
tit AUTOQ43 - Q300_5 motivation not answered.
if(miss(q300_5)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_5.
DELETE VARIABLES flag.

***************************************AUTOQ44.
!SUM_TO_VAR svar=q310x1_1 evar=q310x1_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x2_1 evar=q310x2_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x3_1 evar=q310x3_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x4_1 evar=q310x4_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x5_1 evar=q310x5_98 qnt=AUTOQ44.

***************************************AUTOQ45.
tit AUTOQ45 - Switch % <2 years out of range.
if(q320x1_1 < 0 or q320x1_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x1_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch % 2-<4 years out of range.
if(q320x2_1 < 0 or q320x2_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x2_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch % 4-<12 years out of range.
if(q320x3_1 < 0 or q320x3_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x3_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch % 12-<18 years out of range.
if(q320x4_1 < 0 or q320x4_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x4_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Switch % 18+ years out of range.
if(q320x5_1 < 0 or q320x5_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ46.
!SUM_TO_VAR svar=q330x1_1 evar=q330x1_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x2_1 evar=q330x2_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x3_1 evar=q330x3_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x4_1 evar=q330x4_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x5_1 evar=q330x5_98 qnt=AUTOQ46.

***************************************AUTOQ47.
tit AUTOQ47 - Likelihood to prescribe PRODUCT Y variation 1 not answered.
if(miss(q340_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q340_1.
DELETE VARIABLES flag.

***************************************AUTOQ48.
tit AUTOQ48 - Switch % <2 years out of range.
if(q350x1_1 < 0 or q350x1_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x1_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch % 2-<4 years out of range.
if(q350x2_1 < 0 or q350x2_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x2_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch % 4-<12 years out of range.
if(q350x3_1 < 0 or q350x3_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x3_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch % 12-<18 years out of range.
if(q350x4_1 < 0 or q350x4_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x4_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Switch % 18+ years out of range.
if(q350x5_1 < 0 or q350x5_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ49.
!SUM_TO_VAR svar=q360x1_1 evar=q360x1_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x2_1 evar=q360x2_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x3_1 evar=q360x3_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x4_1 evar=q360x4_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x5_1 evar=q360x5_98 qnt=AUTOQ49.

***************************************AUTOQ50.
tit AUTOQ50 - Likelihood to prescribe PRODUCT Y variation 2 not answered.
if(miss(q370_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q370_1.
DELETE VARIABLES flag.

***************************************AUTOQ51.
tit AUTOQ51 - Switch % <2 years out of range.
if(q380x1_1 < 0 or q380x1_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x1_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch % 2-<4 years out of range.
if(q380x2_1 < 0 or q380x2_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x2_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch % 4-<12 years out of range.
if(q380x3_1 < 0 or q380x3_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x3_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch % 12-<18 years out of range.
if(q380x4_1 < 0 or q380x4_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x4_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Switch % 18+ years out of range.
if(q380x5_1 < 0 or q380x5_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ52.
!SUM_TO_VAR svar=q390x1_1 evar=q390x1_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x2_1 evar=q390x2_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x3_1 evar=q390x3_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x4_1 evar=q390x4_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x5_1 evar=q390x5_98 qnt=AUTOQ52.

***************************************AUTOQ53.
tit AUTOQ53 - Likelihood to prescribe PRODUCT Y variation 3 not answered.
if(miss(q400_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q400_1.
DELETE VARIABLES flag.

***************************************AUTOQ54.
tit AUTOQ54 - Switch % <2 years out of range.
if(q410x1_1 < 0 or q410x1_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x1_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch % 2-<4 years out of range.
if(q410x2_1 < 0 or q410x2_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x2_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch % 4-<12 years out of range.
if(q410x3_1 < 0 or q410x3_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x3_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch % 12-<18 years out of range.
if(q410x4_1 < 0 or q410x4_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x4_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Switch % 18+ years out of range.
if(q410x5_1 < 0 or q410x5_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ55.
!SUM_TO_VAR svar=q420x1_1 evar=q420x1_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x2_1 evar=q420x2_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x3_1 evar=q420x3_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x4_1 evar=q420x4_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x5_1 evar=q420x5_98 qnt=AUTOQ55.

* AUTOQ56: no validation emitted - Single-select categorical item (Q430), no macro or bespoke range/sum logic applies.

***************************************AUTOQ57.
tit AUTOQ57 - Implementation time out of allowed range (0-60 months) when institution has ICV capability.
if(q430 = 1 and (q440_1 < 0 or q440_1 > 60)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q440_1.
DELETE VARIABLES flag.

***************************************AUTOQ58.
tit AUTOQ58 - Receptiveness not answered despite institution having ICV capability.
if(q430 = 1 and miss(q450_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q450_1.
DELETE VARIABLES flag.

* AUTOQ59: no validation emitted - Open-ended text response (maps to q460); no standard macro applies to free-text verbatim fields..

***************************************AUTOQ60.
tit AUTOQ60 - Months for Product X out of allowed range (0-60).
if(range(q470_1,0,60) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q470_1.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 62.
* Checks emitted            : 111.
* Questions omitted         : 10.
* Coverage                  : 83.9% (Partial).
* Omitted questions:
*   - AUTOQ1: Consent gate single-punch with terminate logic; no substantive data validation needed beyond routing..
*   - AUTOQ2: Screener gate single-punch with terminate logic; no substantive data validation needed..
*   - AUTOQ3: Screener gate single-punch with terminate logic; no substantive data validation needed..
*   - AUTOQ5: Consent-style single-punch gate question; no substantive data validation needed..
*   - PT10: Pre-test recruitment gate question with terminate logic; no substantive data validation needed..
*   - PT20: Pre-test recruitment gate question with terminate logic; no substantive data validation needed..
*   - AUTOQ34: Grid item naming for this age-group percentage breakdown could not be confidently mapped to dictionary variables (no matching Q34-style variables found); skipping to avoid guessing..
*   - AUTOQ39: Single-select categorical item (Q260); maps to q260 single variable, no range/sum/multi macro applicable - value range check not part of standard macro set.
*   - AUTOQ56: Single-select categorical item (Q430), no macro or bespoke range/sum logic applies.
*   - AUTOQ59: Open-ended text response (maps to q460); no standard macro applies to free-text verbatim fields..

