* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-16T13:26:42.399738+00:00.
* Survey source: 2026 Arcalyst HCP Ad Tracker W1_Programming_v6.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AE1: no validation emitted - Consent/instructional text with terminate logic captured elsewhere; AE1 itself is a single consent item with no complex range/multi checks needed beyond standard single-punch which is not in macro scope for consent-only items..

***************************************S2.
tit S2 - S2 specialty not answered.
if(miss(s2)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s2.
DELETE VARIABLES flag.

***************************************S3.
tit S3 - S3 not answered.
if(miss(s3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s3.
DELETE VARIABLES flag.

***************************************s4.
tit s4 - S4 state not answered.
if(miss(s4)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s4.
DELETE VARIABLES flag.

***************************************S5.
tit S5 - S5 percentage out of range 0-100.
if(s5_1<0 or s5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s5_1.
DELETE VARIABLES flag.

***************************************s6.
tit s6 - S6 years out of range 0-99.
if(s6_1<0 or s6_1>99) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s6_1.
DELETE VARIABLES flag.

***************************************Q105.
tit Q105 - Q105 first OE box left blank (should say 'none' if unaware).
if(miss(q105_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q105_1.
DELETE VARIABLES flag.

***************************************Q135.
!MULTI_A svar=None evar=None qnt=Q135.

* Q137: no validation emitted - Open-ended text response; no standard macro applies..

***************************************Q140.
!MULTI_B svar=None evar=None qnt=Q140.

***************************************Q205.
tit Q205 - Q205 not answered.
if(miss(q205)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q205.
DELETE VARIABLES flag.

* AUTOQ1: no validation emitted - Instructional/transition text embedded with routing note, not a standalone response variable in dictionary..

* Q210: no validation emitted - Open-ended/brand recall text response; no standard macro applies..

***************************************Q220.
tit Q220 - Q220 not answered.
if(miss(q220)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q220.
DELETE VARIABLES flag.

***************************************Q230.
!MULTI_B svar=None evar=None qnt=Q230.

***************************************Q240.
tit Q240 - Q240 estimated views out of range 1-99.
if(q240_1<1 or q240_1>99) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q240_1.
DELETE VARIABLES flag.

* AUTOQ2: no validation emitted - Instructional text/link repeating Q240 range note, not a separate response variable..

* Q245: no validation emitted - Open-ended text response; no standard macro applies..

***************************************Q250.
!MULTI_A svar=None evar=None qnt=Q250.

***************************************Q255.
!MULTI_B svar=None evar=None qnt=Q255.

* Q305: no validation emitted - Open-ended text question (q305) - no macro validation applicable..

***************************************Q310.
tit Q310 - Q310 ad impression missing.
if(miss(q310)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310.
DELETE VARIABLES flag.

* Q315: no validation emitted - Open-ended text question (q315) - no macro validation applicable..

* Q320: no validation emitted - Open-ended text question (q320) - no macro validation applicable..

***************************************Q325.
tit Q325 - Q325 grid rows 1-5 missing.
if(miss(q325_1) or miss(q325_2) or miss(q325_3) or miss(q325_4) or miss(q325_5)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q325_1 q325_2 q325_3 q325_4 q325_5.
DELETE VARIABLES flag.
tit Q325 - Q325 grid rows 6-11 missing.
if(miss(q325_11) or miss(q325_6) or miss(q325_7) or miss(q325_8) or miss(q325_9) or miss(q325_10)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q325_11 q325_6 q325_7 q325_8 q325_9 q325_10.
DELETE VARIABLES flag.

* AUTOQ3: no validation emitted - Duplicate/auto-generated grid summary of Q325 items; actual variables (q325_1 to q325_11) already validated under Q325; cannot confidently map AUTOQ3 to distinct new variables..

***************************************Q340.
tit Q340 - Q340 recall ad missing.
if(miss(q340)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q340.
DELETE VARIABLES flag.

***************************************Q345.
!MULTI_A svar=None evar=None qnt=Q345.

***************************************Q350.
!MULTI_B svar=None evar=None qnt=Q350.

***************************************Q355.
tit Q355 - Q355 timeframe missing.
if(miss(q355)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q355.
DELETE VARIABLES flag.

***************************************D1.
tit D1 - D1 biological sex missing.
if(miss(d1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d1.
DELETE VARIABLES flag.

***************************************D2.
tit D2 - D2 age out of range or missing.
if(miss(d2_1) or d2_1<0 or d2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d2_1.
DELETE VARIABLES flag.

***************************************D3.
tit D3 - D3 geographic area missing.
if(miss(d3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d3.
DELETE VARIABLES flag.

***************************************d4.
tit d4 - D4 clinical setting missing.
if(miss(d4)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d4.
DELETE VARIABLES flag.

* D5: no validation emitted - Instructional/lead-in text for the follow-up interview invitation (D5); actual response captured in AUTOQ4..

***************************************AUTOQ4.
tit AUTOQ4 - D5 follow-up interest missing.
if(miss(d5)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d5.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 36.
* Checks emitted            : 26.
* Questions omitted         : 11.
* Coverage                  : 69.4% (Partial).
* Omitted questions:
*   - AE1: Consent/instructional text with terminate logic captured elsewhere; AE1 itself is a single consent item with no complex range/multi checks needed beyond standard single-punch which is not in macro scope for consent-only items..
*   - Q137: Open-ended text response; no standard macro applies..
*   - AUTOQ1: Instructional/transition text embedded with routing note, not a standalone response variable in dictionary..
*   - Q210: Open-ended/brand recall text response; no standard macro applies..
*   - AUTOQ2: Instructional text/link repeating Q240 range note, not a separate response variable..
*   - Q245: Open-ended text response; no standard macro applies..
*   - Q305: Open-ended text question (q305) - no macro validation applicable..
*   - Q315: Open-ended text question (q315) - no macro validation applicable..
*   - Q320: Open-ended text question (q320) - no macro validation applicable..
*   - AUTOQ3: Duplicate/auto-generated grid summary of Q325 items; actual variables (q325_1 to q325_11) already validated under Q325; cannot confidently map AUTOQ3 to distinct new variables..
*   - D5: Instructional/lead-in text for the follow-up interview invitation (D5); actual response captured in AUTOQ4..

