* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-16T08:58:31.753457+00:00.
* Survey source: (V3_R93941) 12847_BD_Nexus_Post_Market_Surveillance_Qre_260429_James_02.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* Q0: no validation emitted - Single screening question with terminate logic; no multi/range/rank macro applicable, simple single-punch..

***************************************Q1.
!MULTI_A svar=q1_1 evar=q1_98 qnt=Q1.

***************************************Q2.

* Q3: no validation emitted - Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..

* Q4: no validation emitted - Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..

***************************************Q5.
!RANK_ALL_CHK svar=q5_1 evar=q5_5 qnt=Q5 opr==.

* Q6: no validation emitted - Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..

* Q7: no validation emitted - Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..

***************************************Q8.
!RANK_ALL_CHK svar=q8_1 evar=q8_5 qnt=Q8 opr==.

* Q9: no validation emitted - Single-punch estimation question; no macro applicable..

* Q10: no validation emitted - Single-punch estimation question; no macro applicable..

***************************************Q12.
!MULTI_A svar=q12_1 evar=q12_98 qnt=Q12.


**************** Validation coverage summary ****************************.
* Total questions in survey : 12.
* Checks emitted            : 4.
* Questions omitted         : 8.
* Coverage                  : 33.3% (Partial).
* Omitted questions:
*   - Q0: Single screening question with terminate logic; no multi/range/rank macro applicable, simple single-punch..
*   - Q2: Standard rating grid (1-7 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..
*   - Q3: Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..
*   - Q4: Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..
*   - Q6: Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..
*   - Q7: Standard rating grid (1-5 scale per item); no MULTI/SUM/RANK macro applies to single-answer grids..
*   - Q9: Single-punch estimation question; no macro applicable..
*   - Q10: Single-punch estimation question; no macro applicable..

