* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-16T10:15:52.827436+00:00.
* Survey source: (V9 R98676) CRA-Astellas_Dravet_Syndrome_HCP_Survey_v28May2026.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AUTOQ1: no validation emitted - Consent gate single-punch with terminate logic; no standard macro applies to a binary consent screener item.

* AUTOQ2: no validation emitted - Binary gating/consent question with terminate logic; not a substantive data item requiring macro validation.

* AUTOQ3: no validation emitted - Binary gating/consent question with terminate logic; not a substantive data item requiring macro validation.

* AUTOQ5: no validation emitted - Binary consent-style question; not a substantive data item requiring macro validation.

* PT10: no validation emitted - Pre-test recruitment gating question with terminate logic; not a substantive data item.

* PT20: no validation emitted - Pre-test recruitment gating question with terminate logic; not a substantive data item.

***************************************AUTOQ6.
!MULTI_NUMB svar=s10 evar=s10 qnt=AUTOQ6 ctr=1 opr==.

***************************************AUTOQ7.
!MULTI_NUMB svar=s20 evar=s20 qnt=AUTOQ7 ctr=1 opr==.

***************************************AUTOQ8.
!MULTI_NUMB svar=s30 evar=s30 qnt=AUTOQ8 ctr=1 opr==.

***************************************AUTOQ9.
tit AUTOQ9 - Years in practice out of allowed screener range (3-35).
if(s40_1 < 3 or s40_1 > 35) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s40_1.
DELETE VARIABLES flag.

***************************************AUTOQ10.
!MULTI_NUMB svar=s50 evar=s50 qnt=AUTOQ10 ctr=1 opr==.

***************************************AUTOQ11.
!SUM_TO_VAR svar=s70_1 evar=s70_98 qnt=AUTOQ11.

***************************************AUTOQ12.
!MULTI_NUMB svar=s80_1 evar=s80_1 qnt=AUTOQ12 ctr=1 opr=>=.

***************************************S85.
!SUM_TO_VAR svar=s85_1 evar=s85_5 qnt=S85.

***************************************AUTOQ13.
!MULTI_A svar=s90_1 evar=s90_98 qnt=AUTOQ13.

***************************************AUTOQ14.
!MULTI_NUMB svar=s100_1 evar=s100_1 qnt=AUTOQ14 ctr=1 opr==.
!MULTI_NUMB svar=s100_2 evar=s100_2 qnt=AUTOQ14 ctr=1 opr==.
!MULTI_NUMB svar=s100_3 evar=s100_3 qnt=AUTOQ14 ctr=1 opr==.

***************************************AUTOQ15.
!SUM_TO_VAR svar=q10_1 evar=q10_98 qnt=AUTOQ15.
tit AUTOQ15 - I don't know selected alongside substantive insurance percentages.
if(q10dk_99 = 1 and (sum(q10_1, q10_98) ~= 0)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q10dk_99 q10_1 q10_2 q10_3 q10_4 q10_98.
DELETE VARIABLES flag.

***************************************AUTOQ16.
!SUM_TO_VAR svar=q20_1 evar=q20_2 qnt=AUTOQ16.

***************************************AUTOQ17.
tit AUTOQ17 - Confirmed SCN1A mutation percentage out of valid 0-100 range.
if(range(q30_1, 0, 100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q30_1.
DELETE VARIABLES flag.

***************************************AUTOQ18.
!MULTI_A svar=q40_1 evar=q40_98 qnt=AUTOQ18.

***************************************AUTOQ19.
!MULTI_NUMB svar=q50_1 evar=q50_1 qnt=AUTOQ19 opr==.

***************************************AUTOQ20.
tit AUTOQ20 - Diagnosed prevalence out of allowed range (1-100K) or missing.
if(miss(q60x_1) or q60x_1 < 1 or q60x_1 > 100000) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q60x_1.
DELETE VARIABLES flag.

***************************************AUTOQ21.
!MULTI_NUMB svar=q70 evar=q70 qnt=AUTOQ21 opr==.

***************************************AUTOQ22.
tit AUTOQ22 - Q22 expected increase % missing or out of range when Q70=3.
if(q70 = 3 and (miss(q90_1) or q90_1 < 0 or q90_1 > 100)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q70 q90_1.
DELETE VARIABLES flag.

***************************************AUTOQ23.
!SUM_TO_VAR svar=q100_1 evar=q100_3 qnt=AUTOQ23 opr==.

***************************************AUTOQ24.
!SUM_TO_VAR svar=q110_1 evar=q110_5 qnt=AUTOQ24 opr==.

***************************************AUTOQ25.
!MULTI_B svar=q120x1_1 evar=q120x1_99 qnt=AUTOQ25.
!MULTI_B svar=q120x2_1 evar=q120x2_99 qnt=AUTOQ25.
!MULTI_B svar=q120x3_1 evar=q120x3_99 qnt=AUTOQ25.
!MULTI_B svar=q120x4_1 evar=q120x4_99 qnt=AUTOQ25.
!MULTI_B svar=q120x5_1 evar=q120x5_99 qnt=AUTOQ25.

***************************************AUTOQ26.
!SUM_TO_VAR svar=q130x1_1 evar=q130x1_4 qnt=AUTOQ26 opr==.
!SUM_TO_VAR svar=q130x2_1 evar=q130x2_4 qnt=AUTOQ26 opr==.
!SUM_TO_VAR svar=q130x3_1 evar=q130x3_4 qnt=AUTOQ26 opr==.
!SUM_TO_VAR svar=q130x4_1 evar=q130x4_4 qnt=AUTOQ26 opr==.
!SUM_TO_VAR svar=q130x5_1 evar=q130x5_4 qnt=AUTOQ26 opr==.

***************************************AUTOQ27.
!MULTI_A svar=q140_1 evar=q140_98 qnt=AUTOQ27.

***************************************AUTOQ28.
tit AUTOQ28 - Good seizure control threshold % missing or out of range.
if(miss(q150_1) or q150_1 < 0 or q150_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q150_1.
DELETE VARIABLES flag.

***************************************AUTOQ29.
tit AUTOQ29 - % not achieving good seizure control missing or out of range.
if(miss(q160_1) or q160_1 < 0 or q160_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q160_1.
DELETE VARIABLES flag.

***************************************AUTOQ30.
tit AUTOQ30 - % considered for gene therapy missing or out of range.
if(miss(q170_1) or q170_1 < 0 or q170_1 > 100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q170_1.
DELETE VARIABLES flag.

***************************************AUTOQ31.
tit AUTOQ31 - Open-ended initial thoughts on Product X missing.
if(miss(q180)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q180.
DELETE VARIABLES flag.

***************************************AUTOQ32.
!MULTI_NUMB svar=q190_1 evar=q190_98 qnt=AUTOQ32 opr=<=.
!MULTI_B svar=q190_1 evar=q190_98 qnt=AUTOQ32.

***************************************AUTOQ33.
!MULTI_NUMB svar=q200_1 evar=q200_98 qnt=AUTOQ33 opr=<=.
!MULTI_B svar=q200_1 evar=q200_98 qnt=AUTOQ33.

* AUTOQ34: no validation emitted - No confidently mapped SPSS variable range found for this trial-criterion age distribution grid (q210x variables present but only single per age band with unclear sum target); skipping to avoid guessing incorrectly..

***************************************AUTOQ35.
!MULTI_NUMB svar=q220_1 evar=q220_1 qnt=AUTOQ35 opr==.

***************************************AUTOQ36.
tit AUTOQ36 - Open-ended initial thoughts on Product Y missing.
if(miss(q230)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q230.
DELETE VARIABLES flag.

***************************************AUTOQ37.
!MULTI_NUMB svar=q240_1 evar=q240_98 qnt=AUTOQ37 opr=<=.
!MULTI_B svar=q240_1 evar=q240_98 qnt=AUTOQ37.

***************************************AUTOQ38.
!MULTI_NUMB svar=q250_1 evar=q250_98 qnt=AUTOQ38 opr=<=.
!MULTI_B svar=q250_1 evar=q250_98 qnt=AUTOQ38.

***************************************AUTOQ39.
tit AUTOQ39 - Q260 (Product Y inpatient/outpatient setting) left blank.
if(miss(q260)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q260.
DELETE VARIABLES flag.

***************************************AUTOQ40.
tit AUTOQ40 - Q270_1 (likelihood to prescribe Product Y) left blank.
if(miss(q270_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q270_1.
DELETE VARIABLES flag.

***************************************AUTOQ41.
tit AUTOQ41 - Q280_1 out of allowed range 0-100 or missing.
if(miss(q280_1) or q280_1<0 or q280_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q280_1.
DELETE VARIABLES flag.

***************************************AUTOQ42.
tit AUTOQ42.
if(None) flag = 1.
freq flag.
DELETE VARIABLES flag.

***************************************AUTOQ43.
tit AUTOQ43 - Q300 grid row(s) left blank.
if(miss(q300_1) or miss(q300_2) or miss(q300_3) or miss(q300_4) or miss(q300_5)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q300_1 q300_2 q300_3 q300_4 q300_5.
DELETE VARIABLES flag.

***************************************AUTOQ44.
!SUM_TO_VAR svar=q310x1_1 evar=q310x1_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x2_1 evar=q310x2_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x3_1 evar=q310x3_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x4_1 evar=q310x4_98 qnt=AUTOQ44.
!SUM_TO_VAR svar=q310x5_1 evar=q310x5_98 qnt=AUTOQ44.

***************************************AUTOQ45.
tit AUTOQ45 - Q320x1_1 switch proportion out of range/missing.
if(miss(q320x1_1) or q320x1_1<0 or q320x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x1_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x2_1 switch proportion out of range/missing.
if(miss(q320x2_1) or q320x2_1<0 or q320x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x2_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x3_1 switch proportion out of range/missing.
if(miss(q320x3_1) or q320x3_1<0 or q320x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x3_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x4_1 switch proportion out of range/missing.
if(miss(q320x4_1) or q320x4_1<0 or q320x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x4_1.
DELETE VARIABLES flag.
tit AUTOQ45 - Q320x5_1 switch proportion out of range/missing.
if(miss(q320x5_1) or q320x5_1<0 or q320x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q320x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ46.
!SUM_TO_VAR svar=q330x1_1 evar=q330x1_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x2_1 evar=q330x2_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x3_1 evar=q330x3_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x4_1 evar=q330x4_98 qnt=AUTOQ46.
!SUM_TO_VAR svar=q330x5_1 evar=q330x5_98 qnt=AUTOQ46.

***************************************AUTOQ47.
tit AUTOQ47 - Q340_1 (likelihood to prescribe Product Y variation #1) left blank.
if(miss(q340_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q340_1.
DELETE VARIABLES flag.

***************************************AUTOQ48.
tit AUTOQ48 - Q350x1_1 switch proportion out of range/missing.
if(miss(q350x1_1) or q350x1_1<0 or q350x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x1_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x2_1 switch proportion out of range/missing.
if(miss(q350x2_1) or q350x2_1<0 or q350x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x2_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x3_1 switch proportion out of range/missing.
if(miss(q350x3_1) or q350x3_1<0 or q350x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x3_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x4_1 switch proportion out of range/missing.
if(miss(q350x4_1) or q350x4_1<0 or q350x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x4_1.
DELETE VARIABLES flag.
tit AUTOQ48 - Q350x5_1 switch proportion out of range/missing.
if(miss(q350x5_1) or q350x5_1<0 or q350x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q350x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ49.
!SUM_TO_VAR svar=q360x1_1 evar=q360x1_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x2_1 evar=q360x2_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x3_1 evar=q360x3_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x4_1 evar=q360x4_98 qnt=AUTOQ49.
!SUM_TO_VAR svar=q360x5_1 evar=q360x5_98 qnt=AUTOQ49.

***************************************AUTOQ50.
tit AUTOQ50 - Q370_1 (likelihood to prescribe Product Y variation #2) left blank.
if(miss(q370_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q370_1.
DELETE VARIABLES flag.

***************************************AUTOQ51.
tit AUTOQ51 - Q380x1_1 switch proportion out of range/missing.
if(miss(q380x1_1) or q380x1_1<0 or q380x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x1_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x2_1 switch proportion out of range/missing.
if(miss(q380x2_1) or q380x2_1<0 or q380x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x2_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x3_1 switch proportion out of range/missing.
if(miss(q380x3_1) or q380x3_1<0 or q380x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x3_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x4_1 switch proportion out of range/missing.
if(miss(q380x4_1) or q380x4_1<0 or q380x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x4_1.
DELETE VARIABLES flag.
tit AUTOQ51 - Q380x5_1 switch proportion out of range/missing.
if(miss(q380x5_1) or q380x5_1<0 or q380x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q380x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ52.
!SUM_TO_VAR svar=q390x1_1 evar=q390x1_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x2_1 evar=q390x2_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x3_1 evar=q390x3_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x4_1 evar=q390x4_98 qnt=AUTOQ52.
!SUM_TO_VAR svar=q390x5_1 evar=q390x5_98 qnt=AUTOQ52.

***************************************AUTOQ53.
tit AUTOQ53 - Q400_1 (likelihood to prescribe Product Y variation #3) left blank.
if(miss(q400_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q400_1.
DELETE VARIABLES flag.

***************************************AUTOQ54.
tit AUTOQ54 - Q410x1_1 switch proportion out of range/missing.
if(miss(q410x1_1) or q410x1_1<0 or q410x1_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x1_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x2_1 switch proportion out of range/missing.
if(miss(q410x2_1) or q410x2_1<0 or q410x2_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x2_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x3_1 switch proportion out of range/missing.
if(miss(q410x3_1) or q410x3_1<0 or q410x3_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x3_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x4_1 switch proportion out of range/missing.
if(miss(q410x4_1) or q410x4_1<0 or q410x4_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x4_1.
DELETE VARIABLES flag.
tit AUTOQ54 - Q410x5_1 switch proportion out of range/missing.
if(miss(q410x5_1) or q410x5_1<0 or q410x5_1>100) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q410x5_1.
DELETE VARIABLES flag.

***************************************AUTOQ55.
!SUM_TO_VAR svar=q420x1_1 evar=q420x1_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x2_1 evar=q420x2_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x3_1 evar=q420x3_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x4_1 evar=q420x4_98 qnt=AUTOQ55.
!SUM_TO_VAR svar=q420x5_1 evar=q420x5_98 qnt=AUTOQ55.

***************************************AUTOQ56.
tit AUTOQ56 - Q430 (institution ICV delivery capability) left blank.
if(miss(q430)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430.
DELETE VARIABLES flag.

***************************************AUTOQ57.
tit AUTOQ57 - Q440_1 implementation time out of range/missing when Q430=Yes.
if(q430=1 and (miss(q440_1) or q440_1<0 or q440_1>60)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q440_1.
DELETE VARIABLES flag.

***************************************AUTOQ58.
tit AUTOQ58 - Q450_1 institution receptiveness left blank when Q430=Yes.
if(q430=1 and miss(q450_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q430 q450_1.
DELETE VARIABLES flag.

* AUTOQ59: no validation emitted - Open-ended text response (Q460 equivalent); no standard macro applies to free-text fields..

***************************************AUTOQ60.
tit AUTOQ60 - Q470_1 (months for Product X) out of allowed range 0-60.
if(range(q470_1, 0, 60) = 0 and miss(q470_1) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q470_1.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 62.
* Checks emitted            : 105.
* Questions omitted         : 8.
* Coverage                  : 87.1% (Partial).
* Omitted questions:
*   - AUTOQ1: Consent gate single-punch with terminate logic; no standard macro applies to a binary consent screener item.
*   - AUTOQ2: Binary gating/consent question with terminate logic; not a substantive data item requiring macro validation.
*   - AUTOQ3: Binary gating/consent question with terminate logic; not a substantive data item requiring macro validation.
*   - AUTOQ5: Binary consent-style question; not a substantive data item requiring macro validation.
*   - PT10: Pre-test recruitment gating question with terminate logic; not a substantive data item.
*   - PT20: Pre-test recruitment gating question with terminate logic; not a substantive data item.
*   - AUTOQ34: No confidently mapped SPSS variable range found for this trial-criterion age distribution grid (q210x variables present but only single per age band with unclear sum target); skipping to avoid guessing incorrectly..
*   - AUTOQ59: Open-ended text response (Q460 equivalent); no standard macro applies to free-text fields..

