* Encoding: UTF-8.
* Generated by checkmatrix-claude-engine on 2026-09-16T13:30:30.178567+00:00.
* Survey source: 2026 Arcalyst HCP Ad Tracker W1_Programming_v6.docx.
* Model used for validation-plan analysis: claude-sonnet-5.
* DO NOT hand-edit downstream of this line without regenerating - see AGENTS.md.

* Macro library reproduced verbatim from the organization's verified reference
* script (R76681, Part 1 - tests/system/fixtures/R76681/Part1_till_A13.1.sps,
* lines 13-159). Do not hand-edit; if the organization's macro library changes,
* re-extract from an updated verified reference script instead.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_A (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
temporary.
Disp dic /var=!svar to !evar.
count var1_cnt = !svar to !evar(0 1).
select if var1_cnt <>  !ctr.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.

**************** Procedure to check Multi Punch Questions ****************************.
Define !MULTI_B (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1))

count var_cnt = !svar to !evar(1).

tit !qnt - Nothing selected.
select if var_cnt = 0.
list record, !svar to !evar.

tit !qnt - Invalid Punches.
count var1_cnt = !svar to !evar(0 1).
temporary.
Disp dic /var=!svar to !evar.
select if var1_cnt <>  !ctr.
list record, !svar to !evar.

tit !qnt - None/DK selected with valid codes.
count var_cnt = !svar to !evar(1).
temporary.
select if var_cnt > 1 and !evar=1.
list record, !svar to !evar.
temporary.
count var1_cnt = !svar to !evar(1).
select if var1_cnt =  !ctr.
tit !qnt - Error Flag-ALL Respondents have punch 1 ONLY.
list record, !svar to !evar.
!EndDefine.


*** To be use in case of check Sum must equal to 100 OR Sum atleast to 100% OR atleast SUM to response from other data variable**.

Define !Sum_to_var (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

compute SumX=sum(!svar to !evar).
exe.

tit !qnt - SUM NOT MATCHING TO !ctr.
temporary.
select if SumX !opr !ctr.
list record, !svar to !evar.
del var SumX.
!EndDefine.

************ ONLY selected number of response allowed for MULTI RESPONSE Qs (ex. like only 3, atleast 3 selection allowed) * .

Define !multi_numb (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /ctr !TOKENS (1) /opr !TOKENS (1))

COUNT numb=!svar to !evar (1).
exe.

tit !qnt - SLECTION NOT MATCHIN TO !ctr.
temporary.
select if numb !opr !ctr.
list record, !svar to !evar.
del var numb.
!EndDefine.

************ RANK CHECK * .

Define !Rank_ALL_CHK (svar !TOKENS (1) /evar !TOKENS (1) /qnt !TOKENS (1) /rank !TOKENS (1) /opr !TOKENS (1))

COMPUTE scoreval =nvalid(!svar to !evar).
exe.

tit !qnt - RANK NOT MATCHING TO !rank.
temporary.
select if scoreval !opr !rank.
list record, !svar to !evar.

COMPUTE minrank =min(!svar to !evar).
exe.

COMPUTE maxrank =max(!svar to !evar).
exe.

tit !qnt - INVALID RANKS .
temporary.
select if (minrank !opr 1 OR maxrank !opr scoreval).
list record, !svar to !evar.

EXECUTE.
*Compute scoreval to determine the number of valid values in each row for comparison.
COMPUTE k = 0.
EXECUTE.
*create the output value of k all values =0.
VECTOR X = !svar to !evar.
LOOP #i = 1 to scoreval.
+ LOOP #j = (#i+1) to scoreval.
+ IF X(#i) = X(#j) k=1.
END LOOP.
END LOOP.
EXECUTE .

tit !qnt - RANK DUPLICATE.
temporary.
select if k=1.
list record, !svar to !evar.
del var scoreval k minrank maxrank.

!EndDefine.


**************** Per-question validation calls (questionnaire order) ****************************.
* AE1: no validation emitted - Consent/informational text with routing handled elsewhere; AE1 itself is a single consent punch already covered by screener termination logic, but no standard macro applies to pure consent text display..

***************************************S2.
tit S2 - S2 specialty not answered.
if(miss(s2)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s2.
DELETE VARIABLES flag.

***************************************S3.
tit S3 - S3 not answered.
if(miss(s3)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s3.
DELETE VARIABLES flag.

***************************************s4.
tit s4 - S4 state not answered.
if(miss(s4)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s4.
DELETE VARIABLES flag.

***************************************S5.
tit S5 - S5 percentage out of range or missing.
if(miss(s5_1) or range(s5_1,0,100)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s5_1.
DELETE VARIABLES flag.

***************************************s6.
tit s6 - S6 years practicing out of range or missing.
if(miss(s6_1) or range(s6_1,0,99)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s6_1.
DELETE VARIABLES flag.
tit s6 - S7 grid patient counts missing.
if(miss(s7_1) or miss(s7_2) or miss(s7_3) or miss(s7_4) or miss(s7_5) or miss(s7_6) or miss(s7_7)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag s7_1 s7_2 s7_3 s7_4 s7_5 s7_6 s7_7.
DELETE VARIABLES flag.

***************************************Q105.
tit Q105 - Q105 first OE box (or 'none') not entered.
if(miss(q105_1)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q105_1.
DELETE VARIABLES flag.
tit Q105 - Q110 awareness grid missing responses.
if(miss(q110_1) or miss(q110_2) or miss(q110_3) or miss(q110_4) or miss(q110_5)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q110_1 q110_2 q110_3 q110_4 q110_5.
DELETE VARIABLES flag.

***************************************Q135.
!MULTI_A svar=None evar=None qnt=Q135.

***************************************Q137.
tit Q137 - Q137 open-end not answered.
if(miss(q137)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q137.
DELETE VARIABLES flag.

***************************************Q140.
!MULTI_B svar=None evar=None qnt=Q140.

***************************************Q205.
tit Q205 - Q205 not answered.
if(miss(q205)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q205.
DELETE VARIABLES flag.

* AUTOQ1: no validation emitted - Instructional/routing text tied to Q205, not an independent response item..

***************************************Q210.
tit Q210 - Q210 open-end not answered.
if(miss(q210)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q210.
DELETE VARIABLES flag.

***************************************Q220.
tit Q220 - Q220 not answered.
if(miss(q220)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q220.
DELETE VARIABLES flag.

***************************************Q230.
!MULTI_B svar=None evar=None qnt=Q230.

***************************************Q240.
tit Q240 - Q240 estimated number of times out of range or missing.
if(miss(q240_1) or range(q240_1,1,99)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q240_1.
DELETE VARIABLES flag.

* AUTOQ2: no validation emitted - Instructional text/link paired with Q240 numeric entry; no separate variable..

***************************************Q245.
tit Q245 - Q245 open-end not answered.
if(miss(q245)) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q245.
DELETE VARIABLES flag.

***************************************Q250.
!MULTI_A svar=None evar=None qnt=Q250.

***************************************Q255.
!MULTI_B svar=None evar=None qnt=Q255.

* Q305: no validation emitted - Open-ended text response; no macro validation applies..

***************************************Q310.
tit Q310 - Q310 out of range / missing.
if(range(q310,1,5) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q310.
DELETE VARIABLES flag.

* Q315: no validation emitted - Open-ended text response (base: q310=4,5); no macro validation applies..

* Q320: no validation emitted - Open-ended text response; no macro validation applies..

***************************************Q325.
tit Q325 - Q325 grid rows 1-5 out of range/missing.
if(range(q325_1,1,3)=0 or range(q325_2,1,3)=0 or range(q325_3,1,3)=0 or range(q325_4,1,3)=0 or range(q325_5,1,3)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q325_1 q325_2 q325_3 q325_4 q325_5.
DELETE VARIABLES flag.
tit Q325 - Q325 grid rows 6-11 out of range/missing.
if(range(q325_6,1,3)=0 or range(q325_7,1,3)=0 or range(q325_8,1,3)=0 or range(q325_9,1,3)=0 or range(q325_10,1,3)=0 or range(q325_11,1,3)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q325_6 q325_7 q325_8 q325_9 q325_10 q325_11.
DELETE VARIABLES flag.

***************************************AUTOQ3.
tit AUTOQ3 - AUTOQ3 (Q325 grid) row out of range/missing.
if(range(q325_1,1,3)=0 or range(q325_2,1,3)=0 or range(q325_3,1,3)=0 or range(q325_4,1,3)=0 or range(q325_5,1,3)=0 or range(q325_6,1,3)=0 or range(q325_7,1,3)=0 or range(q325_8,1,3)=0 or range(q325_9,1,3)=0 or range(q325_10,1,3)=0 or range(q325_11,1,3)=0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q325_1 q325_2 q325_3 q325_4 q325_5 q325_6 q325_7 q325_8 q325_9 q325_10 q325_11.
DELETE VARIABLES flag.

***************************************Q340.
tit Q340 - Q340 out of range / missing.
if(range(q340,1,2) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q340.
DELETE VARIABLES flag.

***************************************Q345.
!MULTI_A svar=q345_1 evar=q345_98 qnt=Q345.
!MULTI_B svar=q345_1 evar=q345_98 qnt=Q345.

***************************************Q350.
!MULTI_A svar=q350_1 evar=q350_98 qnt=Q350.
!MULTI_B svar=q350_1 evar=q350_98 qnt=Q350.

***************************************Q355.
tit Q355 - Q355 out of range / missing.
if(range(q355,1,6) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag q355.
DELETE VARIABLES flag.

***************************************D1.
tit D1 - D1 out of range / missing.
if(range(d1,1,2) = 0 and d1 <> 97) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d1.
DELETE VARIABLES flag.

***************************************D2.
tit D2 - D2 age out of range (0-100) / missing.
if(range(d2_1,0,100) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d2_1.
DELETE VARIABLES flag.

***************************************D3.
tit D3 - D3 out of range / missing.
if(range(d3,1,3) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d3.
DELETE VARIABLES flag.

***************************************d4.
tit d4 - D4 out of range / missing.
if(range(d4,1,3) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d4.
DELETE VARIABLES flag.

* D5: no validation emitted - Instructional/lead-in text for follow-up interview invitation, not itself a response item (actual response captured in AUTOQ4)..

***************************************AUTOQ4.
tit AUTOQ4 - D5/AUTOQ4 out of range / missing.
if(range(d5,1,2) = 0) flag = 1.
freq flag.
temp.
sel if flag = 1.
list record flag d5.
DELETE VARIABLES flag.


**************** Validation coverage summary ****************************.
* Total questions in survey : 36.
* Checks emitted            : 34.
* Questions omitted         : 7.
* Coverage                  : 80.6% (Partial).
* Omitted questions:
*   - AE1: Consent/informational text with routing handled elsewhere; AE1 itself is a single consent punch already covered by screener termination logic, but no standard macro applies to pure consent text display..
*   - AUTOQ1: Instructional/routing text tied to Q205, not an independent response item..
*   - AUTOQ2: Instructional text/link paired with Q240 numeric entry; no separate variable..
*   - Q305: Open-ended text response; no macro validation applies..
*   - Q315: Open-ended text response (base: q310=4,5); no macro validation applies..
*   - Q320: Open-ended text response; no macro validation applies..
*   - D5: Instructional/lead-in text for follow-up interview invitation, not itself a response item (actual response captured in AUTOQ4)..

